eng2ch_dict = {
"a.":"GGLL WHJ",
"abandon":"YTY YCAJ",
"abba":"BSKG WQCB",
"abbey":"FTBT IPKF",
"abdullah":"BSKG HHY SFG RUG",
"abids":"",
"abl":"",
"aboard":"WGKU HHGG",
"abroad":"LGYI QHY",
"abrupt":"PWDU QDOU",
"abs":"",
"absorb":"KEYY",
"abu":"BSKG HHY",
"abuj":"BSKG DMHJ SMU",
"abus":"HAAG",
"academ":"IPBF SYI",
"academy":"IPBF BPFQ",
"access":"FJPK",
"accompany":"BUKG",
"accord":"GGLL GCFT",
"account":"MTAY",
"achiev":"BCY TJGF",
"acknowledg":"BDII YWY",
"acquisit":"BCY TJGF",
"acquit":"FQV LDJD",
"across":"PWAT FPI",
"act":"TFHH YLYI",
"ad":"WCU FQB UEJJ",
"adam":"GOGD IVF",
"adapt":"TDPD YID",
"addict":"UBQN",
"addit":"LKG",
"address":"FBN FHG",
"adjust":"YMFK",
"admin":"TPNN",
"admit":"BDII YWY",
"adopt":"WYCM UDYJ",
"adult":"DNNT WWWW",
"advert":"YYGT TFKF",
"aerospac":"TEYM GDI",
"affair":"GKVH",
"affect":"JYIE KTMK",
"afford":"TJGF FHNV",
"afric":"DJDD IYTH",
"aft":"NTFN",
"afternoon":"GHI TFJ",
"aftershock":"WTU FDFE",
"ag":"QVEY",
"agass":"BSKG LKG SGHG",
"agend":"JJJJ TKGG",
"aggress":"WVPC LTKG",
"ago":"NYWY UEJJ",
"agr":"UWYC RCI YID FWYG",
"agree":"MGKD UJNU",
"agricult":"PEI",
"ahead":"UEJJ",
"aid":"DTBH",
"ail":"YSSI ODMY",
"aim":"HHHH RQYY",
"air":"RNB",
"aircraft":"NUI TFHH KKDK",
"airlin":"TEYM PWAF WCU NGKD",
"airpl":"NUI SMN",
"airport":"SMN FNRT",
"airstrik":"PWAF DXYE",
"airwav":"JNV IHCY",
"airway":"TEYM XGT",
"ala.":"BSKG RUG",
"alabam":"GOGD RUG CNHN CNNG",
"alarm":"AQKY RBCY",
"alask":"BSKG RUG ADWR LKG",
"alb":"BSKG QIU CNHN NXV GOGD",
"albert":"AQU WRG FAWK",
"alert":"AQKY NJQR",
"alexand":"GOGD DLV MMMM DDDD",
"alexandr":"GOGD DLV MMMM DDDD",
"all-around":"WGF DMJD",
"all-out":"WGF LTN",
"all-star":"WGF JEG JTGF",
"all-time":"XNN VIU",
"allow":"YTFH",
"almost":"MTN TUHK",
"alon":"QTJY",
"along":"UEJJ",
"alongsid":"UPYB",
"already":"NNNN XCAG",
"also":"BNHN",
"altern":"FWFJ",
"although":"KJU",
"alumin":"QKKG",
"alway":"UKNU",
"amazon":"GOGD CNNG BIPI",
"amazon.com":"GOGD CNNG BIPI",
"ambassad":"DDDD WGKQ",
"ambit":"AIBB LFNH",
"ambush":"WDY FMK",
"amend":"WHTE",
"amid":"KHK",
"among":"PPPP KHK",
"amount":"OVTY",
"amsterdam":"BSKG VXGU ADWR TRFF MYD",
"analys":"WVB SRH",
"analyst":"WVB SRH",
"ancest":"PYEG",
"anderson":"PVF TFLN SSSU",
"andrew":"PVF TFLN QGJF",
"andy":"PVF MPD",
"angel":"GDI WGKQ",
"angl":"QEJ",
"angry":"TGD RNB",
"ankar":"PVF HHU RUG",
"ankl":"KHJS",
"annivers":"XNN WYNN",
"anonym":"AADK QKF",
"answ":"TWGK",
"ant":"JCG JYQY",
"anthony":"PVF AII NXV",
"anti-doping":"RCI IWU DLF YJJH",
"anti-spam":"RCI FUG FEYY MBH WRHH",
"anti-terrorism":"RCI AMYN",
"anti-virus":"RYMN UGMW GXGU",
"anticip":"CBDM OUFH",
"antitrust":"RCI RTAN RUG ADWR",
"antonio":"PVF AII NXV TMOD",
"anyon":"WTFG WSKG WWWW",
"anyth":"WTFG WSKG GKVH",
"anyway":"GII YWXN",
"apart":"BGKH",
"apolog":"UVOW",
"app":"YID ETNH",
"apparel":"YEU",
"appear":"GOI",
"appetit":"WYVE WWKW",
"apply":"YID ETNH",
"appoint":"WTFG WGKB",
"approach":"RUVG RPK",
"approv":"TFQM",
"approxim":"XQYY",
"april":"LHNG EEEE",
"ar":"BSKG HEF QCB",
"arab":"BSKG RUG WRG",
"araf":"FQPV",
"arbit":"SCY DGVT",
"arch":"XNGN",
"archaeolog":"FTGN DGHG",
"architect":"YMCY YFH JGMH",
"area":"DMJD TKWY",
"argentin":"BSKG SVEY TFPD",
"arizon":"GOGD TJH CCCS VFBH",
"arlington":"BSKG VOU GBNM",
"arm":"NKUE",
"armstrong":"BSKG VXGU ADWR TRFF YVCE",
"army":"PLJ",
"arnold":"BSKG YADK TFLN",
"around":"XATQ",
"arrang":"GKIH GJFG",
"array":"BWY",
"arrest":"RGEY",
"art":"ANB SYI",
"arthrit":"UDU ABJ OOU",
"asbesto":"DGTG SRMH",
"ash":"DOU",
"asia-pacific":"GOGD DYI",
"asid":"UPYB",
"ask":"UKD",
"aspir":"IJQN YNEG",
"ass":"NXXV",
"assassin":"JUJG QSU",
"assault":"DXYE FMK",
"assembl":"WYSU",
"assert":"YGD XTAY",
"assess":"WDG",
"asset":"UQWM UTE",
"assign":"WVB SGNN",
"assist":"DTBH",
"assum":"UFYE",
"astronaut":"PGFJ TEYM KMU",
"astronom":"GDI YYGY",
"asyl":"NKUP CWYG",
"athlet":"FCPI FCLN KMU",
"atmosph":"GDI RNB",
"atom":"DRII BBBB",
"atop":"SDMY",
"atp":"",
"attach":"BWFY",
"attack":"FMK",
"attempt":"YAAG",
"attend":"CDER",
"attorney":"TVFH JGMH",
"attract":"XHH",
"au":"GDI YYGY UJFJ WUG",
"auburn":"XAG PUJN QCB",
"audio":"FNR",
"audit":"PJHJ",
"aug.":"WTY EEEE",
"august":"WTY EEEE",
"austin":"TMOD ADWR ISH",
"auth":"FHWU",
"auto":"IRNN LGNH",
"automobl":"IRNN LGNH",
"autonom":"THD YGD",
"av":"",
"avail":"DEF ETNH",
"avenu":"TFFH",
"avert":"TQQY",
"avoid":"NKUP",
"await":"TFFU",
"award":"UQDU",
"away":"QHY",
"ax":"WQRJ",
"baby":"MMVF",
"back":"RGKD",
"back-to-back":"LPK XFND",
"backup":"TLF",
"bad":"FGIY",
"bag":"QNV",
"baghdad":"CNHN STKG DPI",
"bail":"WKSY TOCH",
"bal":"GFIY",
"ballot":"RMCY SFIU",
"ban":"SSFI",
"band":"BWY",
"bang":"KMEE",
"bangkok":"JLCU WWKF",
"bangladesh":"BLF LKG RUG",
"bank":"QVEY TFHH",
"bankrupt":"DHCY LGNH",
"bar":"RIVG",
"barb":"QQCY",
"barcelon":"CNHN PFJF LQU VFBH",
"bargain":"FLWY YYQY",
"barrel":"SCEH",
"bas":"WYPS",
"basebal":"SDWH GFIY",
"basket":"TJTL",
"basketbal":"TJTL GFIY",
"basqu":"HHU ADWR DQB",
"bat":"RRG",
"battery":"JNV IBN",
"battl":"UFK",
"battleground":"HKAT FNRT",
"bay":"IYOX",
"bayern":"CNHN WAT TJH GOGD",
"bbc":"",
"bc":"WCU FQB UEJJ",
"beach":"ICWY",
"beam":"SAG SFH",
"bear":"BDII",
"beat":"RSH",
"beauty":"UGDU",
"becaus":"LDI YLYI",
"beckham":"MHNY DQB ICY VXGU",
"becom":"YOCU",
"bed":"YSI",
"bee":"PNTJ JTDH",
"beef":"RHK MWWI",
"beer":"KRTF ISGG",
"beg":"TNB",
"begin":"GAK VCKG",
"begun":"GAK VCKG",
"behalf":"WAY GEU",
"behead":"DQWY UDI",
"behind":"RGKD",
"beirut":"MHNY QGJF TRFF",
"bel":"WVB MHNY",
"believ":"WYG",
"belong":"NTKY",
"belt":"GKPH",
"bench":"WGKM",
"benchmark":"ADWF UWYG",
"bend":"YOXB",
"benea":"GHI",
"benefit":"TJH",
"berkeley":"WRG DQB TJH",
"berlin":"SRG SSY",
"besid":"UPYB",
"best":"JBCU VBG",
"best-selling":"JHNR QIEG",
"bet":"MFTJ",
"better-than-expected":"FHVK FPI CBDM ADWE",
"beyond":"FHVK",
"bid":"BMK WWJH",
"big":"DDDD",
"biggest":"JBCU DDDD",
"bil":"VEGG FWI",
"billionair":"PGKL WCNF",
"bin":"WBB",
"biotechnolog":"TGD TRQR AAAA ANB",
"bird":"QYNG",
"birmingham":"WRG JEG FJWN",
"birthday":"TGD JJJJ",
"bit":"GGLL HKOU",
"black":"LFOU",
"blackberry":"LFOU ATXU",
"blast":"OTHF",
"blew":"KQWY",
"blind":"YNHF",
"block":"FNWY",
"blockad":"FFFY",
"blockbust":"DNNT ALN",
"blog":"JJJJ FNU",
"blood":"TLD",
"bloody":"TLD EJTG",
"blow":"KQWY",
"blu":"AJTL",
"blu-ray":"AJTL IQB",
"blue-chip":"SKD TFKD",
"bmw":"PGYU CNNG",
"board":"SRCY",
"boast":"THD DFNB",
"boat":"TEMK",
"bob":"HKOU UDI",
"bobby":"AQKY PWFI",
"bod":"PEU WOY",
"body":"TMDT",
"bog":"RQKG INXN",
"bold":"DDDD EJGG",
"bomb":"OTHF XUJF",
"bond":"TWIK",
"boo":"KHAG",
"book":"NNHY",
"boom":"KWCN KWCN",
"boost":"FULJ",
"boot":"AFWX",
"born":"TGD",
"borrow":"WAJG",
"boss":"FTXB SRCY",
"boston":"IHCY FGHG GBNM",
"bottl":"UAGN",
"bottom":"YQAY",
"bought":"NUDU",
"bound":"LWJJ",
"bout":"GGLL BLH",
"bow":"TMDX",
"bowl":"DPQB",
"box":"WGKL",
"boy":"LLB BYNW",
"brad":"QSH",
"brady":"YPMB",
"brain":"EYBH",
"branch":"FCU",
"brand":"THGF",
"brav":"CELB",
"brawl":"UFK",
"brazil":"CNHN SGHG",
"breach":"FNHP RCI",
"break":"ONRH",
"breakthrough":"PWDU DHCY",
"breath":"RNB",
"brem":"EEEE CKF",
"brew":"SGYE",
"bridg":"STDJ",
"brief":"TDGU",
"bright":"YPMB",
"bring":"GKPH GOI",
"brink":"LPV",
"brit":"AMDU LGYI WWWW",
"britain":"AMDU LGYI",
"broad":"PAMQ",
"broadband":"PAMQ GKPH",
"broadcast":"YYGT RTOL",
"bronz":"GEF QMGK",
"broth":"KQB UXHT",
"brought":"GKPH",
"brown":"SPFI",
"brows":"NHD",
"brush":"NMHJ",
"brussel":"DMHJ QGJF PFJF QIU",
"buck":"DCWY",
"bud":"AAHT",
"budget":"CBDM THAJ",
"buffalo":"JFCB RHK",
"bug":"JHNY",
"build":"VFHP",
"built":"VFHP",
"built-in":"MAFW TYI",
"bulk":"DDDD JGJF",
"bullet":"BBBB XUJF",
"bump":"RUJF",
"bunch":"GKII",
"bundl":"RLSY",
"buoy":"IEBG SFIY",
"burd":"QMU RJGG",
"bureau":"NNKD",
"burn":"OATQ",
"burst":"OJAI OTHF",
"bury":"FJFG",
"bus":"WCU UQU",
"bush":"IAKY IIII",
"businessm":"UMWK WWWW",
"busy":"NYNN",
"button":"QVFP",
"buy":"NUDU",
"buyout":"NHTY MQCY",
"buzz":"",
"bypass":"NKUP",
"cabinet":"SANG",
"cabl":"XJTQ",
"cairo":"GAK LQU",
"calm":"GEQH",
"cambridg":"WGIJ STDJ",
"camera":"SHG SMN",
"camp":"APKK",
"campaign":"HKAT",
"canad":"LKG WGKR DDDD",
"cancel":"BCY IIEG",
"candid":"YXIF FHF",
"cant":"GII",
"cap":"MHJH",
"captain":"TEMK TAYI",
"car":"LGNH",
"carbon":"DMDO",
"card":"HHU",
"cargo":"WXMU",
"carry":"GKPH",
"cart":"DDDD LGNH",
"cartel":"HHU TRFF QIU",
"casey":"YAKG NFHW",
"cash":"GMQN QQQQ",
"casino":"MFTJ FNRT",
"cast":"REN",
"casual":"WJMY QDOU",
"cat":"QTAL",
"catalog":"HHHH VIU",
"catastroph":"POU CWYG",
"catch":"RRHY",
"caught":"RRHY",
"cease-fir":"WYPS OOOO",
"ceasefir":"WYPS OOOO",
"cellphon":"JNV YTDG",
"celt":"HHU QIU TRFF WWWW",
"cent":"WVB",
"century":"ANV XNN",
"ceo":"",
"ceremony":"WYQY AAD",
"cert":"NTE",
"certain":"DQEH",
"chain":"QLPY",
"chair":"SDSK",
"chairm":"YGD YAMH",
"challeng":"RIQN HKAT",
"champ":"KELF",
"chancel":"WFIU FFCY",
"channel":"UTHP",
"chant":"KJJG",
"char":"WYOU",
"charg":"XJMU",
"charley":"RMG TELB",
"chart":"GEU",
"chat":"BQTB",
"cheap":"WGJQ PEGF",
"check":"SJGF",
"checkpoint":"SWGI SJGF HKOU",
"chees":"VEN SGTK",
"chelse":"AVN QIU SGHG",
"chem":"WXN IPBF",
"chest":"EQQB",
"chicago":"APU LKG SKSK",
"chick":"CQYG",
"chief":"YGD",
"child":"BYNW",
"childr":"BYNW BBBB",
"chin":"GHI CNHN",
"chines":"KHK LGYI",
"chip":"DYWF",
"chipset":"ANU THGN",
"choos":"TFQP",
"christian":"ADWF HICH",
"christmas":"CFF YTHP",
"chrysler":"DQB AGOU ADWR AFLN",
"church":"FTBT IPKF",
"cia":"KHK MDI NGEG RBCY NNKD",
"cigaret":"OLDY",
"cincinnat":"UYGH UYGH VFBH RJGH",
"circ":"LKMI",
"circuit":"JNV KHTK",
"city":"FDNT YMHJ",
"civil":"WCU NAV",
"claim":"TQIY",
"clash":"UKHH PWDU",
"class":"XEYY",
"class-action":"WYSU WSGG YRYY YWCY",
"clear":"UQVH",
"cleveland":"DQB TJH FWI UFF",
"click":"HKOU FMK",
"climb":"RHYC",
"clinch":"RQNN",
"clinton":"DQB SSY GBNM",
"clip":"GUWI",
"clock":"QKHH",
"clon":"DQB BTGG",
"clos":"RPK",
"closest":"JBCU RPK",
"cloth":"DMHJ",
"cloud":"FCU",
"club":"WHWY QII UKBH",
"clust":"XEGG",
"clutch":"RRHY",
"cnn":"DEF XGT USRH UBD MQQI",
"cnn/money":"MFTT XCAG",
"coach":"FTBT XANW",
"coal":"OAFS",
"coast":"MDFJ",
"coca-col":"SKD QII",
"cocain":"SKD HHU LDI",
"cod":"WXMU GCFJ WFY FFIW",
"coff":"KLKG KDJD",
"cold":"UWYC",
"colin":"TUFH SSY",
"collab":"WGKF",
"collaps":"WGCJ",
"colleagu":"MGKD GKVH",
"collect":"WYSU",
"colleg":"DDDD IPBF",
"collid":"RUJF",
"colon":"XFKG ENRT",
"colony":"GQFH NAV",
"color=":"UTEM QCB",
"colorado":"TUFH LQU RUG QQU",
"colt":"RHFK LCAG",
"column":"GQJH",
"com":"GOI",
"comb":"SYCQ",
"combin":"XEGG WGKF",
"comeback":"LKD",
"comfort":"WFKB",
"command":"WGKB WYCU",
"commerc":"QYVM JQRR",
"commit":"BDII YADK",
"commod":"CNNG SCEH",
"common":"MGKD",
"commun":"WCU PYFG",
"commut":"UDGT",
"compact":"XFKG PUDU",
"company":"WCU NGKD",
"compat":"AWU DHBD",
"compens":"MUKG",
"compet":"QVHJ",
"competit":"UKQB QVHJ",
"compil":"XYNA",
"complain":"RQNN QBNU",
"complaint":"RQNN QBNU",
"complet":"PFQB GKIH",
"complex":"TJTU VSU",
"comply":"EBCY WWY",
"composit":"TJTU WGKF",
"compound":"TJTU",
"comprehend":"GJFG QEVH",
"comput":"THAJ",
"computerworld":"YFH THAJ SMN ANV LWJJ",
"con":"CYNA",
"conceiv":"SHNU",
"concern":"RJGG NYNY",
"concert":"UJF QII WFCU",
"concess":"YHG",
"conclud":"XFKG YWXN",
"concret":"HWU WSGG",
"condemn":"YKHP GMU",
"conduc":"PUDU YTBN",
"config":"SGNN LFHF",
"confirm":"YGHG PUDU",
"conflict":"UKHH PWDU",
"confront":"DMJD CFY",
"confus":"OPI AKGN",
"congo":"MQJH JSI",
"congoles":"MQJH JSI WWWW",
"congress":"LGYI WFCU",
"connect":"LPK",
"connecticut":"YVII IJFG QTOY STKG YTYH",
"consecut":"LPK XFND RQYY",
"consequ":"XFKG JSI",
"conserv":"ITHF",
"consid":"FTGN HANI",
"consist":"XEGG DNNT",
"consol":"RPWA RMHJ",
"consolid":"LKG LDD",
"consort":"SGNN WJMY",
"conspir":"AWU YAFS",
"constitut":"SQCY DNNT",
"construct":"SQCY TFKP",
"consult":"UQWK YQJG",
"consum":"IIEG XJMU",
"cont":"LPK XFND RQYY",
"contact":"RUVG QEJY",
"contain":"WYNK",
"contamin":"IFNN IVSU",
"contend":"UFK",
"contenty":"MWI PWWK",
"contest":"XXN PFJM",
"continu":"XONN XFND",
"contract":"WGKF MGKD",
"contradict":"CBTR RFHD",
"contribut":"AMU FMUD",
"control":"RPWA RMHJ",
"controvers":"QVHJ YYQY",
"controversy":"QVHJ YYQY",
"converg":"SHG UQU",
"convers":"RCI",
"convert":"YOCU",
"convict":"UDJH",
"convoy":"TEMQ BWY",
"cook":"YBOU",
"cool":"UWYC",
"coop":"TDXB",
"cop":"AQKY PWFI",
"copyright":"THGC SCY",
"corn":"GYI OYTY",
"corp.":"WCU NGKD",
"correct":"CFY",
"correspond":"SHG TWFU",
"corrupt":"YWFW",
"cost":"WWJH QGT",
"cost-cutting":"IEJH UDGT DNNT SGD",
"could":"CEXX",
"council":"YYQY WFCU",
"counsel":"CLN",
"count":"OVTY",
"counterfeit":"WYLY",
"counterpart":"CFY YID",
"country":"LGYI",
"county":"EGCU",
"coup":"GHTY YOCU",
"coupl":"DNNT CFY",
"cours":"FJPK TKGG",
"court":"IFCY YTFP",
"courtroom":"PJHJ UDJH PGCF",
"covet":"WYNM FIYI",
"cow":"XGUI RHK",
"cowboy":"RHK WBG",
"crack":"GQJE",
"crackdown":"QFHW DFYI",
"craft":"AAAA ANB",
"crash":"DUOG RUJF",
"crat":"TSHF BBBB",
"credit":"WYG ETNH",
"crew":"WWWW KMU",
"cricket":"SRCY GFIY",
"crim":"LDJD",
"crimin":"LDJD QTBN",
"crippl":"HCDM",
"crop":"YFD TPEY",
"cross":"FGH PBF",
"crowd":"RYJH",
"crown":"PFQF",
"crud":"OEGG OTFP",
"crunch":"",
"crush":"DFYI",
"cryst":"JJJF WSGG",
"cub":"XLN",
"cult":"AHTB FTBT",
"cup":"SGIY",
"cur":"GOGN",
"curb":"RPWA RMHJ",
"curs":"YEGG KKMB",
"curt":"FQV GJFG",
"custody":"WKSY TPNN",
"custom":"NUD WWWK",
"cut":"AVN",
"dairy":"EBNN",
"dam":"FMY",
"damp":"IFJE",
"dan":"WDMC",
"dar":"NBTY",
"dark":"JUJG",
"dash":"UKHH",
"databas":"OVTY RNDG YLK",
"daunt":"LGEU NHWY",
"davenport":"NNHY HJSU",
"dawn":"TQTI JEG",
"day":"GDI",
"dead":"GQXB",
"deadliest":"JBCU GCFT WGKB RQYY",
"deadlin":"FAWY HHHG JJJJ ADWE",
"deadlock":"WGLG NNKD",
"deal":"UQU JQRR",
"dealt":"UQU JQRR",
"dean":"BPFQ TAYI",
"death":"GQXB",
"debt":"WGMY",
"debut":"UTHF UQWY",
"dec.":"FGH FGG EEEE",
"decad":"FGH RHFK",
"deceiv":"CYNA",
"decid":"UNWY PGHU",
"declin":"BTAH",
"decreas":"UDGT",
"deep":"IPWS",
"deeply":"IPWS",
"defect":"RMNW BQVG",
"defend":"BYN",
"defens":"BYN",
"deficit":"FOU PBF",
"defin":"PGHU YQI",
"definit":"JEG DQEH",
"defy":"RCI RYMN",
"delay":"RWYG NYPI",
"delight":"NWGJ NNWY",
"delivery":"NTCY UDPI",
"demand":"SVF FIYI",
"den":"ULGK PWU",
"dent":"MMGD",
"deny":"GIKF YWY",
"depart":"BMK NTCY",
"depend":"TFKD",
"deploy":"UKBH LFTJ",
"deport":"CAQY EPI",
"deposit":"DHBD FFIW",
"depot":"WBB YLK",
"depress":"IEGG FUEU",
"deputy":"GKLJ",
"derail":"EUKQ LVN",
"derby":"TFLN XXN",
"descend":"GHI",
"describ":"RALG SYPI",
"desert":"IITT IAJD",
"deserv":"YID",
"design":"YMCY YFH",
"desir":"IJQN YNEG",
"desk":"HJSU",
"desktop":"HJSU DMJD",
"despit":"NYUU TPNN",
"destin":"RXJG PGHU",
"destroy":"DHCY FGIY",
"destruct":"VAMC",
"detail":"XLG ABJ",
"detain":"RQKG QYVL",
"detect":"SJGF",
"determin":"WTHF BMK",
"devast":"RMWY VAMC",
"develop":"NTCY NAEI",
"devil":"IJXX NHJU",
"devot":"DWFH FMUD",
"dhak":"DPI HHU",
"diagnos":"YWET",
"dialog":"CFY YTDG",
"diamondback":"KTMK NTFN JPXN",
"dick":"NKMH",
"dict":"KKKK SYPI",
"didn":"IMCY DEF",
"die":"GQXB",
"died":"GQXB",
"diesel":"HXSU IMG",
"diet":"ABJ WYVE",
"diff":"GII MGKD",
"difficult":"CWYG",
"dig":"RPWN",
"digit":"OVTY",
"din":"KGMJ VSU",
"dip":"ASGO",
"diplom":"YYGY WTFM",
"direct":"FHF",
"dirty":"EYFG",
"dis":"FQV PYNN",
"disappear":"IIEG RWI",
"disappoint":"RWI YNEG",
"disarm":"XRYT SAAH",
"disc":"TELF",
"disciplin":"XNN TVFH",
"disclos":"FKHK",
"discount":"RRH RKG",
"discovery":"NTCY GMQN",
"discrimin":"AQI KLJH",
"discuss":"YFY YWXN",
"diseas":"UGMW",
"disgrac":"BHG",
"disk":"DUXX TELF",
"dismantl":"RRYY",
"dismiss":"IGEG GJFG",
"disney":"MPD ADWR NXV",
"disord":"TDNN",
"displac":"BCY WAY",
"display":"NAEI",
"disput":"KITT",
"disrupt":"KHK ONRH",
"distinct":"JEG JOGF",
"distribut":"WVB SGNN",
"district":"AQI",
"divers":"QQU",
"divert":"LFNY",
"divid":"WVB",
"dividend":"EMCY THNU",
"dna":"",
"dock":"IAWN",
"dodg":"TMDS",
"doe":"HXWY",
"dog":"QTQK",
"dol":"FIYT IYJH QQQQ",
"doll":"GFQN HWU",
"dolphin":"ITXU EEY",
"dom":"SDMY",
"domain":"WYCM FAKG",
"doom":"FCLN",
"door":"UYHN",
"dop":"IWU DLF YJJH",
"dos":"YJJH",
"dot-com":"",
"doubl":"CCY",
"double-digit":"GMWW WUG OVTY",
"doublehead":"CCY UDI",
"doubt":"NGIY XTDH",
"doughnut":"TDAF TDAF LUDB",
"downgrad":"BTAH XEYY",
"download":"GHI FALK",
"downtown":"YMHJ AQI",
"downward":"TMKD GHI",
"doz":"GGLL RSH",
"dr.":"ATDI TGD",
"draft":"AJJ TYMK",
"drag":"RTBN",
"dram":"ITR JGJF",
"draw":"GLBJ",
"drawn":"GLBJ",
"dream":"SSQU",
"dress":"YEU EBCY",
"drew":"GLBJ",
"drift":"ISFI",
"drink":"KJQN",
"driv":"GAK LGNH",
"drop":"RHJH",
"drought":"JFJ POU",
"drov":"GAK LGNH",
"drug":"AXQY",
"dry":"FGGH",
"dual":"CCY",
"dual-core":"CCY SYNW",
"dub":"SGNN UJF",
"dublin":"FTJB SRG SSY",
"due":"GCFJ ADWE",
"duel":"UNWY UFK",
"duk":"WCU ELVF",
"dump":"LFNY DHBD",
"dun":"DOU PUJN QCB",
"dunt":"TGJF FMK",
"dust":"DOU",
"dutch":"AWSK UFF",
"duty":"GMU WTFG",
"dvd":"",
"e-commerc":"JNV BBBB UMWK TLB",
"e-mail":"JNV BBBB MBH WRHH",
"e-mails":"JNV BBBB MBH WRHH",
"eagl":"YWWG",
"ear":"BGHG",
"earliest":"JBCU JHNH",
"earn":"AQTD TJGF",
"earthquak":"FBN FDFE",
"eas":"PWWK JQRR",
"east":"AII",
"eastern":"AII DMJD RQYY",
"easy":"PWWK JQRR",
"eat":"KTNN",
"ebay":"",
"echo":"LKD FNR",
"eclips":"EEEE QNJY",
"eddy":"IYTH IKMW",
"edg":"LPV",
"edit":"XYNA LKBG",
"edward":"EPDC TFLN WXFJ",
"effect":"UQTY JSI",
"effort":"VCLB LTN",
"egypt":"FCTD EYI",
"eight":"WTY",
"elbow":"EFY",
"eld":"YMKF HWBC",
"elect":"TFQP",
"electron":"JNV BBBB",
"elen":"AQU WWXN",
"elev":"SFIY YMKF",
"eliot":"AQU LTKG TRFF",
"elit":"OGEG AMDU",
"ellison":"FCTD JFD SSSU",
"elud":"IQPV NKUP",
"email":"JNV BBBB MBH WRHH",
"embargo":"SSFI HHHG",
"embarrass":"DNJL DNWJ",
"embassy":"DDDD WGKQ QNPN",
"embattl":"GODR BLH NYWY TFFY",
"embed":"MAFW TYI",
"embrac":"REH RQNN",
"emc":"",
"emerg":"BMK GMQN",
"emit":"NTCY",
"emot":"DFNB XTAY",
"empir":"UPMH LGYI",
"employ":"ETNH",
"empty":"PWAF",
"end":"XFKG GKII",
"endors":"FCU RFFY",
"enemy":"TDTY",
"energy":"CEXX JGJF",
"enforc":"LKG XKJY",
"engin":"NTCY FCLN SMN",
"england":"AMDU STKG UFF",
"enjoy":"YBF",
"enough":"QKQQ",
"enrich":"PGKL",
"entertain":"NNWY QII",
"entir":"WGF",
"entry":"FJPK",
"envoy":"WGKQ FTJF",
"eq":"NGEG UMWK",
"equip":"UFYE TLF",
"erod":"QNJY",
"erp":"WHF OGD UQWM IDRI FWMQ AJH",
"erupt":"OJAI NTCY",
"escap":"IQPV",
"eu":"AQQW JELF",
"euro":"AQQW FQB",
"europ":"AQQW IYTH",
"eurozon":"AQQW FQB AQI",
"every":"TXGU",
"everyon":"TXGU WWWW",
"evil":"AHTB GOGN",
"evolv":"FJPK WXN",
"exact":"UWYG DQEH RQYY",
"examin":"SWGI SJGF",
"exampl":"WGQJ",
"excel":"PWDU BMK",
"excess":"FPI",
"exchang":"RQMD",
"excit":"IRYT FCLN",
"exclud":"RANG XQCN",
"excus":"WAJG KKKK",
"execut":"RVYY TFHH",
"exhibit":"NAEI BMK",
"exil":"IYCQ YTY",
"exit":"BMK KKKK",
"expand":"RYT",
"expect":"CBDM YFH",
"expend":"XJMU",
"expens":"XJMU ETNH",
"expert":"FNYI PEU",
"expir":"GCFJ ADWE",
"explain":"QEVH TOCH",
"explod":"OTHF",
"exploit":"GAK NTCY",
"export":"BMK KKKK",
"expos":"JAWI FKHK",
"express":"NNWY UXHP",
"extend":"RYT",
"extern":"ATDI TGD",
"extinct":"GOI XQCN",
"extradit":"XHH IYAC",
"extrem":"SEYY YACI",
"face=":"EWGI",
"facil":"LCAG YXIF",
"fact":"GKVH PUDU",
"fad":"MQI IMKF",
"fail":"MTY",
"fair":"WCU GHD",
"fak":"WNHC",
"falcon":"WYFJ",
"fals":"QAJG",
"fam":"QKF",
"famili":"PEU YTFP",
"fan":"YNND",
"fanny":"NXXV EMCY",
"far":"FQPV",
"farm":"PEI FNRT",
"fast":"NNWY",
"fast-growing":"TAYI TJGF NNWY",
"fastest":"JBCU NNWY",
"fat":"EUFH",
"fault":"QAJG",
"favorit":"JBCU EPDC",
"favourit":"JBCU EPDC",
"fear":"NRG",
"feat":"ALN XGMY",
"fed":"",
"fee":"XJMU",
"feel":"DGKN IPMQ",
"feet":"EFCB",
"fellow":"WFCU KMU",
"felt":"DGKN IPMQ",
"fend":"JVKO DBDM",
"fest":"WYSU WFCU",
"field":"FBN",
"fierc":"QTBL",
"fig":"FQV AWXB JSI",
"fight":"HKAT UFK",
"fil":"UFYE IAGW",
"file-sharing":"YYGY WRHH WVB YBF",
"file-swapping":"YYGY WRHH UQU RQMD",
"film":"JNV JYIE",
"fin":"QGFJ",
"find":"RAT",
"fingerprint":"RXJG XYY",
"finland":"AWVB UFF",
"fir":"UWYC SET",
"firewal":"BYN OOOO FFUK",
"firm":"JCFF",
"first":"TXHT GGLL",
"first-ever":"UTHF UQWY",
"first-round":"TXHT GGLL LKD WGKF",
"fish":"QGF",
"fit":"TDPD WGKF",
"fiv":"GGHG",
"five-month":"GGHG WHJ EEEE",
"five-year":"GGHG RHFK",
"fix":"LDD PGHU",
"flag":"YTAW",
"flam":"OOOO OQVG",
"flar":"OOOO",
"flash":"UWI IQB",
"flat":"GUHK",
"flaw":"GNHC UHXV",
"fle":"IQPV",
"fled":"IQPV",
"fleet":"TEMQ BWY",
"flew":"NUI",
"flex":"YOXB",
"flight":"TEYM TFHH",
"flock":"VTKD",
"flood":"IAWY IIII",
"florid":"WXFJ GMYY",
"flow":"IYCQ",
"flu":"IYCQ DGKN",
"flurry":"NYNN",
"flush":"UKHH",
"fly":"NUI",
"focus":"TGJF HKOU",
"foil":"TIRF",
"fold":"PUNR",
"folk":"WWWW WUN",
"follow":"KHVE",
"font":"PBF WSGG",
"food":"WYVE TRQR",
"fool":"DWJJ",
"foot":"EFCB",
"footbal":"KHU GFIY",
"forc":"LTN",
"ford":"PYGL TRFF",
"forecast":"CBDM IMJH",
"foreign":"QHY LGYI",
"forest":"SSSU SSY",
"forg":"WYLY TFKP",
"forget":"YNNU YNN",
"forgot":"YNNU YNN",
"form":"GAET",
"fort":"WKSF",
"fortun":"FCPI RNB",
"forward":"UEJJ",
"fossil":"WXN DGTG",
"fought":"RSH",
"foul":"IFNN",
"four":"LHNG",
"four-year":"LHNG RHFK",
"fox":"QTRY QTJF",
"fragil":"JQRR DYWF",
"framework":"SQCY LKSU",
"frank":"FJGG YXIF",
"fraud":"CYNA",
"free":"QKQB XJMU",
"free-agent":"TFHH FCLN THD MHNG",
"freedom":"THD MHNG",
"freestyl":"THD MHNG IYNI",
"freez":"UAIY",
"french":"IFCY LGYI",
"frenzy":"UMQI QTGG",
"fresh":"USRH QGUD",
"friday":"JTGF ADWE GGHG",
"friend":"EEG DCU",
"fright":"KGHY",
"front":"UEJJ",
"froz":"UAIY",
"fruit":"IIII JSI",
"fuel":"OQDO OUFH",
"ful":"IAGW",
"fulfil":"IAGW KHU",
"fumbl":"TSGF RBMH",
"fun":"QII FHBC",
"fund":"ADWF QQQQ",
"fury":"VCNU",
"gadget":"IHTY SMN SAAH",
"gain":"NHTY",
"galaxy":"JTGF TXIU",
"gallon":"LKG WXB",
"gambl":"MFTJ FGEF",
"gang":"DTBH",
"gap":"PWAF",
"gas":"RNB",
"gasolin":"IRNN IMG",
"gat":"UYHN",
"gateway":"DDDD UYHN",
"gaug":"IMJH JGJF",
"gav":"XWGK",
"gay":"MGKD NTGG YONU",
"gaz":"UXTH PYMQ",
"gear":"HWBJ LWXN",
"gen":"SHG UDU WYG THNU",
"genes":"ADWF LDI",
"genocid":"TKHH YTTD GOI XQCN",
"germ":"TKHH BBBB",
"germany":"TFLN LGYI",
"get":"TJGF GCFJ",
"giant":"AND",
"gift":"PYNN",
"girl":"VVVV BYNW",
"giv":"XWGK",
"glass":"GHCY GYBC",
"glaz":"TOMG",
"glen":"MGUW WWKF",
"glimps":"UMIH",
"glitch":"DTY BUJH",
"glob":"FBN GFIY",
"gloom":"JUJG",
"glory":"APSU",
"gmail":"",
"go":"FCU",
"go-ahead":"GAK VCKG",
"goal":"HHHH SFIY",
"god":"PYJH",
"going":"FCU",
"gold":"QQQQ",
"golf":"YMKF QIU FWI",
"good":"VBG",
"googl":"WWKF SKSW",
"goos":"TRNG",
"got":"TJGF GCFJ",
"govern":"ICKG GJFG",
"grab":"RRHY",
"grac":"WDNN AHTY",
"grad":"XEYY",
"grand":"UFG CMQN",
"grant":"CQB YTFH",
"graph":"LTUI",
"grav":"FYY",
"gray":"DOU",
"gre":"",
"greatest":"JBCU WFNH DDDD",
"greec":"QDMH EAJG",
"greek":"QDMH EAJG WWWW",
"green":"XVIY",
"greet":"QBPK RUVG",
"grew":"TGD TAYI",
"grey":"DOU QCB",
"grid":"MQQI STKG",
"griev":"DJDN WTLN",
"grim":"GODR VIJK",
"grip":"RRHY PRHJ",
"grocery":"VSU WXMU YHKD",
"gross":"OEGG WWWK",
"ground":"FBN",
"group":"XEGG",
"grow":"TGD TAYI",
"grown":"TGD TAYI",
"guard":"AQKY BGD",
"guerrilla":"IYTB FMK BWY",
"guess":"QTGE",
"guest":"PTKF",
"guid":"NFU",
"gulf":"ITXU IYOX",
"gun":"SWBN",
"gunm":"OQNN OOOO",
"guy":"PEU WOY",
"gymnast":"WSGG RKKS FCPI FCLN KMU",
"habit":"NUD NXFM",
"hack":"DQWY",
"hail":"FQNB",
"hal":"XKJY UFG",
"half":"UFK",
"halftim":"KHK FNRT WSY THNU",
"halfway":"KHK WTPI",
"halliburton":"KWGK TJH WRG GBNM",
"halo":"IQB JPLJ",
"halt":"WYPS",
"ham":"OOOO EVEP",
"hamilton":"ICY PNTM QIU GBNM",
"hampshir":"ICY UOGJ VTKB",
"hand":"RTGH",
"handheld":"RTGH RJGH",
"handl":"QEVH UNWY",
"handset":"KRH TMGK",
"hang":"RFFG",
"happy":"GAK NYNY",
"har":"JFCB QKQY",
"hard":"DGJQ",
"harm":"PDHK",
"harmony":"TKG YXXR",
"harrington":"KWGK VOU GBNM",
"harry":"CCYJ RDNN",
"harsh":"GODR",
"harvard":"KWGK WXJH",
"hat":"MHJH",
"hat-trick":"MHJH BBBB CAT IFCY",
"haul":"DDDD RXXN",
"hav":"DEF",
"hawk":"YWWG",
"hazard":"BWGI",
"head":"UDI",
"headlin":"SFIY JGHM",
"heal":"ICKG WGEN",
"healthy":"WVFP YVII",
"hear":"KRH",
"heard":"KRH",
"heart":"NYNY",
"heat":"RVYO",
"heav":"IWFH",
"heavy":"TGJF",
"heavyweight":"TGJF JGJF XEYY",
"hedg":"TYBC",
"heel":"RGKD KHVE",
"hefty":"WVFP UFG",
"height":"TMDT YMKF",
"held":"RNGF",
"help":"DTBH",
"hen":"XGUI CQYG",
"herald":"WFNY WYCU PNHN",
"hero":"AMDU DCWY",
"hid":"ADNT",
"high":"YMKF",
"high-definition":"YMKF IGEG",
"high-level":"YMKF XEYY",
"high-profile":"YYGT EPCU UDU IYGG",
"high-speed":"YMKF GKIP",
"high-tech":"YMKF TUFH RFCY",
"highest":"JBCU YMKF",
"highlight":"PWDU BMK",
"highway":"YMKF GKIP WCU KHTK",
"hik":"RHYC",
"hil":"MMMM",
"hint":"JUJG FIU",
"hip":"NGCF IWEF",
"hir":"YNWY",
"hit":"FMK",
"hockey":"MAD SJXX GFIY",
"hol":"IMGK",
"hold":"RNGF",
"holiday":"WNHC ADWE",
"hollywood":"VBG AGOU FQNG",
"holy":"PYJH CFF RQYY",
"hom":"PEU",
"homeland":"PYEG LGYI",
"hometown":"PEU XTE",
"hon":"YSSD",
"hook":"QQCY",
"hop":"KHIQ",
"horn":"QEJ",
"hornet":"DDDD AMWU OWVN",
"host":"YGD WWWW",
"hostil":"TDTY",
"hot":"RVYO",
"hotel":"PRGW QNPN",
"hottest":"JBCU RVYO RQYY",
"hour":"IHTY JFY",
"hous":"YNYV BBBB",
"household":"GGLL PEU",
"houston":"WSY ADWR YBTY",
"howard":"FWYF WXFJ TFLN",
"hoy":"KITU",
"hub":"KHK NYNY",
"hug":"RQNN",
"hum":"KYBH",
"hung":"RFFG",
"hunt":"RSH QTAJ",
"hurdl":"KHDN SUFG",
"hurt":"WTLN",
"husband":"DYI FWI",
"husky":"IITT KGOG",
"hybrid":"IJXX WGKF",
"ibm":"",
"icon":"LTUI SFIY",
"id":"TMDT WWVN",
"idea":"SHNU IFCY",
"ill.":"UGMW",
"imagin":"SHNU",
"imf":"LGYI BFIY WXMU TMHK ADWF QQQQ XEGG XKWY",
"immun":"QKQB UMCI",
"imp":"FQDM UJFF",
"impact":"JYIE KTMK",
"imply":"JUJG FIU",
"import":"FJPK KKKK",
"impos":"XKJY LKG",
"impress":"QQWY WMGH",
"imprison":"UDU RLH",
"improv":"RJGH YMKF",
"inc.":"WCU NGKD",
"inch":"AMDU FGHY",
"incit":"OYNN FCLN",
"includ":"QNV RTDG",
"incom":"NHTY TYI",
"increas":"FULJ",
"indefinit":"WYNK ODEG",
"independ":"QTJY UUUU",
"index":"FPXI XHH",
"indian":"QGBH YACI",
"indict":"RPWA TFKF",
"industry":"AAAA OGD",
"infect":"WFNY IVSU",
"inform":"CEPK TDKG",
"inject":"IYGG",
"injury":"WTLN",
"ink":"LFOF",
"inquiry":"YQJG UKD",
"insid":"JFD DMJD",
"insight":"IMGK PWFI",
"insist":"SVF FIYI",
"inspect":"SJGF",
"inspir":"FKUC RLGH",
"instead":"DMJJ GII JGHU",
"institut":"SMN SQCY",
"instruct":"FTBT NFU",
"intel":"AMDU TRFF QIU",
"intellect":"TDKJ LTN",
"intend":"SHNU SVF",
"interact":"UQU GXGD",
"interest":"IWU FHBC",
"interfac":"RUVG KKKK",
"interim":"ADWE UJD",
"intern":"RQKG QYVL",
"internet":"GXGD BUDY MQQI",
"interview":"DMJD YAAG",
"introduc":"WJJ XVKG",
"intrud":"WVPC",
"invad":"WVPC LTKG",
"invest":"RMCY UQWM",
"involv":"CDER GNGD",
"ip":"",
"ipo":"",
"ipod":"",
"iraq":"WVTT RUG DQB",
"ireland":"EPDC QIU UFF",
"iron":"QRWY",
"islam":"WVTT ADWR UFF",
"islamabad":"WVTT ADWR UFF WKSF",
"island":"QYNM",
"isp":"GXGD BUDY MQQI EBCY TLB RJGH WAWY UMWK",
"israel":"NYWY QCB GQJH",
"issu":"BMK THGC",
"item":"TRQR WRHH",
"jack":"SOU DQB",
"jackson":"SOU DQB BIPI",
"jail":"JTYL QTYD",
"jam":"FFTJ",
"jap":"JJJJ SGD WWWW",
"japanes":"JJJJ SGD WWWW",
"jazz":"ELVF FGHG",
"jean":"RHK WBG PUYL",
"jersey":"ICFH SGHG",
"jerusalem":"BBH KHTK RAET UWYC",
"jet":"KFAM RNB AAD NUI SMN",
"jew":"QTDN DYI WWWW",
"jintao":"QRMH IDTF",
"job":"AAAA WTHF",
"jobless":"RWI OGD",
"johannesburg":"XQYY FJWN MWI ADWR WKSF",
"john":"VSFI PTKF",
"johnny":"PEU WOY",
"join":"LPK RUVG",
"joint":"UDU ABJ",
"jok":"TTDU YTDG",
"jolt":"FDFE",
"josh":"CAT GAJ",
"journey":"YTEY TKGG",
"joy":"YMKF IWU",
"judg":"IFCY PNHN",
"july":"AGN EEEE",
"jump":"KHIQ",
"junk":"FUG FEYY",
"jury":"BUKG PJHJ LFTE",
"kashmir":"DQB WFH OYTY QIU",
"kathmandu":"LKG TFLN IAGW FTJB",
"keen":"TXGT QUKQ RQYY",
"keep":"WKSY RFFY",
"ken":"YWY TDKG AIBB LFNH",
"kennedy":"HEF NXV MPD",
"kent":"HEF TRFF VTKB",
"kentucky":"HEF FAWK ADWF",
"kept":"WKSY RFFY",
"kevin":"GAK QIU YYGY",
"key":"UDU QVFP",
"keyboard":"QVFP TELF",
"kick":"KHJR",
"kid":"BYNW",
"kidnap":"XDTB LKSU",
"kiev":"ADWF LGEY",
"kind":"DCU VBG RQYY",
"king":"LGYI GGGG",
"kingdom":"GGGG LGYI",
"kit":"AAAA HWU",
"knew":"TDKG UTHP",
"knight":"CDSK FGHG",
"knock":"YMKC",
"knockout":"FMK WGCJ",
"know":"TDKG UTHP",
"knowledg":"TDKG YKWY",
"known":"TDKG UTHP",
"kraft":"AAAA ANB",
"kremlin":"DQB JFD VXGU SSY PKKF",
"krispy":"EQDB",
"kurd":"YLK QIU TFLN",
"kuwait":"TUFH DGVT TRFF",
"lab":"PUDU CWGI PGCF",
"label":"SFIY TWGI",
"lack":"RMNW",
"lad":"LLB BYNW",
"lady":"VVVV FGHG",
"lag":"AITK RGKD",
"laid":"YTY",
"lak":"IDEG",
"lam":"ULKW",
"lan":"NNKD FAKG MQQI",
"land":"BFMH FBN",
"landmark":"FBN SFIY",
"landscap":"MQI JYIU",
"landslid":"FJNG",
"lank":"FQV IQB",
"lap":"DDDD EVEP",
"laptop":"TTFN YNN SGD JNV EYBH",
"larg":"DDDD",
"largest":"JBCU DDDD",
"lash":"AFWQ",
"last":"JBCU RGKD",
"last-minute":"JBCU RGKD GGLL YNTJ",
"lat":"JQKQ",
"latest":"JBCU JQKQ",
"latin":"RUG SGH",
"laugh":"TTDU",
"launch":"GHI IIII",
"law":"IFCY TVFH",
"lawsuit":"YRYY YWCY",
"lay":"YTY",
"lcd":"IYWY JJJF JOGF FIU KKDK",
"lead":"WYCM NFU",
"leagu":"BUDY JELF",
"leak":"INFY",
"lean":"WTUF",
"leap":"KHIQ",
"learn":"IPBF",
"leas":"TEGG",
"least":"JBCU ITR",
"leav":"YBMC",
"lebanes":"TQTI CNHN VGKT",
"lebanon":"TQTI CNHN VGKT",
"led":"WYCM NFU",
"lee":"UXEF MQI",
"left":"DAF",
"leg":"EVEP",
"legend":"WFNY DSKF",
"lend":"WAJG",
"lengthy":"TAYI ADWE",
"lenovo":"BUDY SHNU",
"less":"ITR",
"lesson":"YJSY",
"let":"YHG",
"level":"XEYY",
"liabl":"SKD CEXX RQYY",
"liberty":"THD MHNG",
"licens":"YTFH SKD",
"lie":"TMDK",
"lift":"IWFH",
"light":"IQB",
"lik":"FKUK CQWY",
"limit":"SEYY BVEY",
"line-up":"CFY YJJ",
"lineup":"CFY YJJ",
"ling":"QGFV QGF",
"link":"BUDY TXIU",
"linux":"",
"lion":"QTJH BBBB",
"liquid":"IYWY WSGG",
"list":"IGEG UJFJ",
"littl":"IHTY",
"liv":"ITDG",
"liverpool":"TJH TRQR IGEY",
"load":"QMU TGJF",
"loan":"WAMU FFIW",
"lobby":"DSK",
"lock":"QIMY",
"lockout":"WYPS AAAA",
"locust":"JRGG JHNY",
"log":"JJJJ FNU",
"london":"WWXN YBTY",
"long":"TAYI",
"long-distance":"TAYI KHAN",
"long-runn":"TAYI ADWE",
"long-term":"TAYI ADWE",
"longest":"JBCU TAYI",
"longhorn":"TAYI QEJ",
"look":"RHF",
"loom":"XKWY DMHJ SMN",
"loos":"ITFQ RTGH UJD",
"loot":"MYFG TRQR",
"lord":"YGD",
"loss":"RWI",
"lost":"RWI",
"lot":"QQU",
"loud":"DDDD FNR",
"low":"WQAY",
"low-cost":"WQAY DNNT SGD",
"lowest":"JBCU WQAY",
"ltd.":"DEF BVEY WCU NGKD",
"luck":"FCPI RNB",
"lump":"FNWY",
"lunch":"TFJ HQCE",
"lung":"EGMH",
"lur":"YTEN",
"luxembourg":"HNE SSSU WKSF",
"luxury":"DFTJ",
"lying":"YAYQ",
"lynch":"THI GQXB",
"machin":"SMN KKDK",
"mad":"UMQI",
"madison":"GTU MPD BIPI",
"madrid":"CNNG TFLN JFD",
"mag":"VSU FNU",
"magazin":"VSU FNU",
"magnitud":"DDDD",
"maid":"VVVV WHY",
"mail":"MBH",
"main":"YGD SVF",
"mainfram":"YGD SMN",
"mainland":"DDDD BFMH",
"mainstream":"YGD IYCQ",
"maintain":"XWYG RYNT",
"mak":"WDTY",
"mal":"LLB",
"malays":"CNNG GOI",
"man":"LLB",
"many":"QQU",
"map":"FBN LTUI",
"mar":"DHCY FGIY",
"marathon":"CNNG RUG SWCY",
"march":"DGGG EEEE",
"margin":"LPV",
"mark":"GYGG",
"market":"YMHJ FNRT",
"marketplac":"WYSU YMHJ",
"marlin":"SWBN QGF",
"marqu":"CNNG DQB",
"marry":"XFKG VQAJ",
"marsh":"IVKG ICFH",
"marshal":"FQB JMHH",
"mart":"WYSU YMHJ",
"martin":"AUKO",
"marvel":"DSKF YOPI",
"mary":"GCG GMYY",
"maryland":"CNNG JFD UFF",
"mask":"DMJD LHJJ",
"mass":"DDDD JGJF",
"massachuset":"CNNG ABUT YFTJ PFJF",
"mast":"YTAW SFH",
"mastermind":"TDKJ GKHE",
"mat":"RVYF",
"match":"AQV SGNN",
"matchup":"SGNN",
"maverick":"DJDD IPKH FWMQ",
"maxim":"STKG YYYY",
"may":"SKD CEXX",
"mcdonald":"GTU IVF APLB",
"mean":"UJNU LNU",
"meant":"UJNU LNU",
"meanwhil":"MGKD JFY",
"meat":"MWWI",
"med":"FBN KHK ITXU",
"medal":"UQDU THGF",
"medic":"ATDI TGD",
"medicin":"AXQY",
"meet":"JMHP",
"melt":"GKMJ",
"memo":"TLF YNNU VIU",
"men":"LLB WWWW",
"mercantil":"UMWK OGD",
"mercury":"IIII JTGF",
"merg":"WGKF UAJ",
"mess":"TDNN",
"met":"JMHP MQB",
"method":"YYGN IFCY",
"mexico":"LFOF SGHG SKSK",
"mic":"GTU DQB MQI",
"michael":"DNPV DQB QIU",
"michel":"OYTY JQWW QIU",
"mickelson":"OYTY DQB QIU SSSU",
"micro":"TMGT",
"microprocess":"TMGT THI GJFG",
"microsoft":"TMGT LQWY",
"microsystem":"TMGT TXIU XYCQ",
"middl":"KHK UJD",
"middlesbrough":"OYTY TFLN QIU ADWR WKSF",
"midfield":"KHK FNRT",
"midnight":"TFJ YWTY",
"mids":"KHK UJD",
"midst":"KHK UJD",
"midway":"KHK WTPI",
"might":"SKD CEXX",
"mighty":"XKJY",
"mild":"IJLG TKG",
"mileston":"JFD TKGG DRTF",
"militia":"NAV RGWU XEGG XKWY",
"militiam":"NAV RGWU",
"mind":"UDI EYBH",
"minim":"FGG WVB UJF TWFU",
"minut":"WVB",
"mir":"INXN ISJH",
"mislead":"YKGD NFU",
"miss":"NKUP GAK",
"missil":"NFU XUJF",
"mississipp":"PNTM SGHG SGHG XXN",
"mistak":"RWI YKGD",
"mit":"ITR",
"mix":"IJXX",
"mob":"GGLL DTBH",
"model":"SAJD GAJF",
"modern":"GMQN WAY",
"modest":"YUVO HAOG",
"mohammad":"LFOD PWFJ LFOD TFLN",
"mom":"VCG VCG",
"moment":"JFY YNTJ",
"monday":"JTGF ADWE GGLL",
"money":"QGT",
"month":"EEEE",
"mood":"NYNY NGEG",
"moon":"EEEE YPMB",
"moor":"WYPS",
"mor":"GJQI QQU",
"moscow":"AJDU ADWR TUFH",
"mosqu":"IGEG FHWU FFU",
"moss":"ACKF AQGD",
"moth":"JTRT",
"motley":"IJXX VSU RQYY",
"mound":"FFFF FWYG",
"mount":"MMMM",
"mountain":"WGKU",
"mourinho":"MMMM",
"mourn":"YEU NHJH",
"mous":"VNUN",
"mov":"TQQY FCLN",
"mp3":"",
"mr.":"TFQB TGD",
"ms":"VVVV FGHG",
"msn":"",
"much":"QQU",
"mul":"CLXI",
"multibillion-dollar":"MTN FGH WNN",
"multipl":"WUKG",
"muse":"IPMN LNU",
"muslim":"TRIE ADWR SSY",
"must":"NTE EDMY",
"mut":"FQV FNR",
"mvp":"JBCU DEF WWJH WFHG GFIY KMU",
"mystery":"PYJH TNTT",
"nam":"QKF",
"narrow":"PWTF",
"nasdaq":"XMWY ADWR DPI DQB",
"nashvil":"VFBH WFH XWYG QIU",
"nasty":"CWYG EPCU",
"nationwid":"WGF LGYI NTGG",
"nato":"UXN DDDD SGHG IUDH WCU XQYY XEGG XKWY",
"nav":"GHD DSK",
"navy":"ITXU PLJ",
"nba":"",
"nbc":"WGF LGYI YYGT RTOL WCU NGKD",
"near":"RPK",
"nearby":"BWFY RPK",
"nec":"WGF LGYI RVYY TFHH TVF KMU WFCU",
"neck":"EFPB",
"nelson":"YNED GHI RNGF CADM",
"nepales":"NXV IRG QIU",
"nerv":"PYJH XCAG",
"net":"MQQI",
"netherland":"AWSK UFF",
"network":"MQQI XTKG",
"nevad":"MWI WXFJ DPI",
"new":"USRH",
"newest":"JBCU USRH",
"next":"GHI GGLL WHJ",
"next-generation":"GHI GGLL WAY",
"nfc":"LGYI PEU KHU GFIY BUDY JELF",
"nfl":"WGF UGDU SNBT SJTQ GFIY BUDY JELF",
"nhl":"WGF LGYI MAD SJXX GFIY BUDY WGKF WFCU",
"nic":"VBG",
"nick":"MMGD",
"niger":"NXV JJJJ QIU",
"night":"YWTY",
"nightclub":"YWTY UKNU WFCU",
"nik":"DMJF DQB",
"nin":"VTN",
"nobel":"YADK MHNY QIU",
"nobody":"IMCY WWWW",
"non":"IMCY DEF",
"norm":"GHD IPKH",
"northeast":"AII UXN",
"northeastern":"AII UXN RQYY",
"northern":"UXN YYGN RQYY",
"northwest":"SGHG UXN",
"northwestern":"SGHG UXN RQYY",
"norway":"RVFB DGVT",
"nos":"THLJ",
"notch":"UVEI",
"notebook":"TTFN YNN SGD",
"nov.":"FGH GGLL EEEE",
"novel":"IHTY YUKQ",
"nuclear":"SYNW CEXX",
"nugget":"IHTY FNWY",
"numb":"YSSI SSSS",
"nurs":"RYNT FGHG",
"o'neal":"TMOD NXV QIU",
"oakland":"TMOD DQB UFF",
"object":"TRQR",
"oblig":"XKJY RPD",
"observ":"CMQN PWFI",
"obstruct":"RIVG",
"obtain":"AQTD",
"occupy":"HKF",
"occur":"NTCY TGD",
"oct.":"FGH EEEE",
"od":"FPI JGJF",
"offend":"JHF QTBN",
"offens":"UEJJ QTDH",
"offseason":"IOOY TBF",
"offset":"RQAY IIEG",
"ohio":"WTRT YNTW WTRT",
"oil":"IMG",
"oil-rich":"PGKL IMG",
"old":"HJG",
"oldest":"JBCU HJG",
"on\friday":"JTGF ADWE GGHG",
"on\thursday":"JTGF ADWE LHNG",
"on\tuesday":"JTGF ADWE FGG",
"on\wednesday":"JTGF ADWE DGGG",
"one-day":"GGLL GDI",
"one-strok":"GGLL FMK",
"one-tim":"GGLL UQWY",
"one-year":"GGLL RHFK",
"onlin":"XGT HHGG",
"ontario":"PVF DDDD LTKG",
"opec":"AQQW WMGH DQB",
"open-source":"GAK IDRI",
"opin":"YWY YLYI",
"opportun":"TDPD PEGF",
"oppos":"RCI CFY",
"opposit":"CFY UUUU DMJD",
"opt":"TFQP RCFH",
"orang":"SWGU",
"orbit":"LVN UTHP",
"oregon":"WTRT AFLN MQI",
"origin":"FHNV IDRI",
"orlando":"TMOD UFF QQU",
"os":"RKKS WTHF TXIU XYCQ",
"oslo":"TMOD ADWR BFMH",
"ottaw":"INGF DYI WXFJ",
"oust":"RWYG TOLN",
"outbreak":"OJAI NTCY",
"outcom":"XFKG JSI",
"outfield":"QHY FNRT",
"outfit":"UFYE TLF",
"outlaw":"FNHP IFCY",
"outlet":"YMHJ FNRT",
"outlin":"LWXN YYBB",
"outlook":"CMQN HKOU",
"output":"LWGJ BMK",
"outright":"PFQB WGF",
"outsid":"QHY DMJD",
"outskirt":"LPV XXEY",
"outsourc":"QHY QNV",
"overcam":"DQB EBCY",
"overcom":"DQB EBCY",
"overlook":"WYWF PYMQ",
"overnight":"GKIH JQKQ",
"oversea":"LGYI QHY",
"overshadow":"BEG JYIE",
"oversight":"NHYQ QRNU",
"overt":"WCU GAK",
"overtak":"FHVK",
"overtim":"LKG GYTG",
"overturn":"RRQW TOLN",
"overwhelm":"IDJN",
"p.m.":"GHI TFJ",
"p2p":"HKOU CFY HKOU",
"pac":"HIR",
"pack":"QNV",
"pact":"FLWY PGHU",
"pag":"DMU",
"paid":"WFY XJMU",
"pain":"UCEK",
"paint":"ISWI",
"pair":"CFY",
"pakistan":"CNHN ADWF ADWR FJGG",
"pal":"AWBB RRRR",
"palac":"PKKF",
"palestin":"CNHN AFLN ADWR FJGG",
"palm":"IPKR",
"pan":"QKMW",
"panel":"SRCY",
"pap":"IYCQ WYVE",
"par":"IAN YXIF",
"parachut":"BTAH AITK WUHJ",
"parad":"IYTB TFHH",
"parcel":"QNV YJSE",
"park":"WCU LFQV",
"part":"UKBH WVB",
"party":"IPKQ",
"pass":"CEPK FPI",
"passport":"RYNT JVKO",
"password":"PNTM DCG",
"past":"FPI",
"pat":"RRG",
"patch":"PUHY SGH",
"path":"KHTK",
"patriot":"EPDC LGYI FTJF",
"patrol":"VPV LQPI",
"pattern":"SAJD AAD",
"paul":"WKSY LQU",
"pav":"QGEY",
"pay":"WFY",
"pda":"WHJ WWWW OVTY PBF EGLN GJFG",
"peac":"TKG GUHK",
"peacekeep":"XWYG TKG",
"peak":"MMMM SDMY",
"peer":"MGKD",
"peer-to-pe":"HKOU CFY HKOU",
"pen":"TTFN",
"penal":"LYJJ",
"pennington":"FKUE PSJ GBNM",
"pent":"SSFI UFTE",
"pentagon":"GGHG LPV GAET",
"peopl":"WWWW WUN",
"per":"TXGU",
"perceiv":"PWFI IPMQ",
"perfect":"PFQB UGDU",
"perform":"WDTY",
"perhap":"AKGD YTFH",
"period":"JFY UJD",
"perm":"INRO",
"permit":"YTFH SKD",
"persist":"RFFY XFND",
"person":"WWWW",
"personnel":"KMU AAAA",
"persuad":"YUKQ EBCY",
"peru":"QGJF",
"pet":"PDXB TRQR",
"petit":"IHTY",
"peyton":"WMGH GBNM",
"pharm":"LFNY ADWF LDI AXQY TRQR PEI FNRT",
"phas":"BWJH WDMC",
"philippin":"ADJD TVFH PRGW",
"phillip":"NUI TJH IGEY",
"phoenix":"MCI MRGD",
"phon":"JNV YTDG",
"photo":"JVKO THGN",
"photograph":"JVKO THGN",
"pick":"RIQN",
"pict":"HCI DQB TRFF",
"pierc":"PWAT BNN",
"pil":"FWYG",
"pilot":"NUI TFHH KMU",
"pin":"SWCY SCFY",
"pip":"TPNN",
"pipelin":"TPNN UTHP",
"piston":"ITDG PFJF",
"pit":"FYMN",
"pitch":"FNRT",
"pittsburgh":"AQV UXXU WKSF",
"plac":"FBN YYGN",
"plagu":"UJLD UMCI",
"plan":"YFH AJH",
"planet":"TFHH JTGF",
"plant":"SFHG TRQR",
"plat":"TELF",
"platform":"GUHK CKF",
"play":"GFQN",
"playoff":"LKG PFJM",
"plead":"TNB FIYI",
"pleas":"YGEG",
"pledg":"YADK YYYY",
"plenty":"DDDD JGJF",
"plot":"FNWY",
"plug":"RTFV",
"plummet":"JAWI KHRW",
"plung":"KHRW AITK",
"pm":"GHI TFJ",
"pocket":"WAYE",
"pod":"AGUW JSI",
"point":"HKOU",
"pois":"QFHW PGHU",
"poison":"GXGU",
"pol":"SEYY",
"poland":"IHCY UFF",
"policy":"GHTY TGMI",
"polit":"PYNN EERQ",
"pollut":"IFNN IVSU",
"pond":"FYVK",
"pool":"IBN",
"poor":"PWLB",
"poorest":"JBCU PWLB",
"pop":"DGUH",
"port":"IAWN",
"port-au-prince":"DYI BBBB IAWN",
"portfolio":"AWU GKVH QNV",
"portland":"IHCY TRFF UFF",
"pos":"UQWV RVYL",
"posit":"WNHC YMCY",
"possess":"REH DEF",
"post":"MBH",
"postpon":"RWYG NYPI",
"pot":"QKMW",
"pound":"DUPY",
"pour":"WGCJ",
"poverty":"PWLB",
"pow":"HKAT WEBG",
"pray":"PYRH PYDF",
"predict":"CBDM YYYY",
"prep":"UWYG TLF",
"prescrib":"FWMQ PGHU",
"preserv":"WKSY RYNT",
"presid":"YGD RFFY",
"press":"DFYI",
"pretty":"ISFI IYCQ",
"prevail":"IYCQ TFHH",
"preview":"CBDM TFKF",
"pric":"WWJH",
"prid":"CTDJ WGQT",
"priest":"WFIU NGKD",
"prim":"UTHF SVF",
"princess":"WCU YGD",
"principl":"DRII MJH",
"print":"QGBH",
"prison":"JTYL QTYD",
"priz":"UQDU",
"pro-democracy":"NAV YGD",
"prob":"YMFK SJGF",
"problem":"UKD JGHM",
"process":"FPI TKGG",
"produc":"TGD UTE",
"profess":"FNR TQIY",
"profil":"WMJH DMJD",
"profit":"TJH IUGG",
"profit-taking":"AQTD TJH LKD KFG",
"program":"TKGG YCBK",
"progress":"FJPK HIR",
"prohibit":"SSFI HHHG",
"project":"ADMY HHHH",
"prol":"FQV UTE FTJF",
"prom":"RLGH WFCU",
"promot":"WKHY FJPK",
"prompt":"UWYG JFY",
"proof":"YGHG RNDG",
"prop":"FCU SYGG",
"propel":"RWYG",
"property":"MFTT UTE",
"propos":"RJGH BMK",
"prosecut":"FHNV YRYY",
"prospect":"QDMH YNEG",
"protect":"WKSY RYNT",
"protest":"RYMN YYQY",
"protocol":"FLWY YYQY",
"prototyp":"DRII GAJF",
"prov":"YGHG JEG",
"provid":"RJGH WAWY",
"provok":"IRYT VCNU",
"pub":"ISGG KCN",
"pump":"DIU",
"pun":"CCY UDU",
"punch":"UDRJ",
"punt":"GUHK YQAY TEMK",
"purchas":"NUDU",
"purport":"SFIY SUPY",
"purpos":"HHHH RQYY",
"pursuit":"WNNP EPI",
"push":"RWYG",
"put":"YTY",
"pyongyang":"GUHK FYKE",
"quak":"YLKM RUFH",
"quart":"DFNB EUKQ",
"quarter-finals":"LHNG WVB PPPP GGLL UNWY PFJM",
"quarterback":"LHNG WVB BGD",
"queen":"VVVV RGF",
"quest":"VFU FIYI",
"quick":"NNWY",
"quiet":"PVF GEQH",
"quit":"TDUH",
"quot":"XHH ETNH",
"quota":"BVEY PTKM",
"rac":"KHQN",
"rack":"LKSU",
"radio":"FQV XGT JNV",
"rag":"DHCY DMHJ",
"raid":"PWDU DXYE",
"rail":"LVN",
"rain":"FGHY",
"rais":"IWFH",
"ram":"MWI DHBD",
"ramp":"AMHK UTHP",
"ran":"KHQN",
"randy":"VBG QCB",
"rang":"TKHH ODU",
"rank":"TFFU XEYY",
"rap":"YMKC",
"rapid":"NNWY",
"rapt":"FNYI NYNY",
"rar":"PWFJ MQB",
"rat":"GKIP YACI",
"rav":"KQNN KFTB",
"raw":"TGD",
"ray":"TMDF XGT",
"re-election":"GMFD TFQP IWFH",
"reach":"GCFJ",
"react":"RCI YID",
"read":"YFND",
"ready":"YIDN XFTJ",
"reaffirm":"TGJF JHK",
"real":"FHWU",
"reason":"GJFG MHNG",
"rebel":"UDRC TDNN",
"rebound":"RCI XUJF",
"rebuild":"TGJF VFHP",
"receiv":"NHTY",
"reclaim":"GAK VEFF",
"recommend":"RWYG ADHB",
"reconstruct":"TGJF VFHP",
"record":"YNN VIU",
"record-breaking":"DHCY XNN VIU",
"recovery":"YVII TJTU",
"recruit":"TGHG AJDL",
"red":"XAG",
"redskin":"QGBH TXHT PVF WWWW",
"reduc":"UDGT",
"reel":"UDBB LMG",
"refer":"RJGH EYI",
"refin":"RJGH OANW",
"refinery":"OGEG OANW DGT",
"reflect":"RCI JMDY",
"reform":"NTY YVEI",
"refug":"YXXV RYNT",
"refund":"VEPI GIPI",
"refus":"RANG XQCN",
"regain":"NHTY LKD",
"regard":"FTGN HANI",
"regim":"GHTY SCY",
"regret":"RGKD NTXU",
"regular-season":"IPKH FWMQ PFJM",
"reign":"DNNL TFHH",
"rein":"XGLG XKJN",
"reinforc":"FULJ LKG",
"reject":"RANG XQCN",
"relax":"YTY SWCY",
"relay":"LFNY RTOL",
"releas":"TOCH YTY",
"relentless":"LDD RVYY RQYY",
"reliev":"UDGT LCAG",
"rely":"WYEY TFKD",
"remain":"QYVL",
"remark":"YWXN",
"remind":"RJGH SGJG",
"remot":"FQPV",
"remov":"GKPH FHU",
"renew":"XFND TWGI",
"rent":"TEGG",
"rep":"WAY GEU",
"repair":"WHTE",
"replac":"WAY FWFJ",
"report":"RBCY TFKF",
"repres":"QFHW DFYI",
"reput":"QKF FNR",
"request":"SVF FIYI",
"requir":"FDMJ SVF",
"rescu":"QEVH FIYT",
"research":"DGAH PWVB",
"resembl":"WQJE",
"reserv":"WYFJ TLF",
"resid":"WYGG",
"resign":"TDUH",
"resist":"RQAY",
"resolv":"UNWY PGHU",
"resort":"RVKG OVTY",
"resourc":"UQWM IDRI",
"respect":"USGF",
"respond":"TWGK",
"respons":"TWGK TJTU",
"rest":"WSY THNU",
"restart":"TGJF YNKD",
"restrict":"BVEY RMHJ",
"result":"XFKG JSI",
"resum":"TUJF DLV",
"retail":"FWYC WYKF",
"retain":"QYVL",
"retir":"VEPI WSY",
"return":"RCPI LKD",
"revamp":"TOLN USRH",
"revel":"QTGG CQWY",
"reveng":"TJTU WVN",
"revenu":"NHTY TYI",
"revers":"RCI",
"review":"PJHJ",
"revolv":"YTNH LFNY",
"reward":"RBCY SGYH",
"rfid":"FQV XGT TMDF HIDM YKWY KLJH",
"rib":"ELN MEF",
"ric":"OYTY",
"rich":"PGKL",
"richest":"JBCU PGKL",
"rick":"RNFG",
"rid":"RLFC EUKQ",
"rifl":"TOLN SJGF",
"rig":"YMCY TLF",
"right":"CFY",
"right-hander":"DKF RTGH",
"rim":"LPV",
"ring":"AAK RXJG",
"riot":"CCYJ TDNN",
"rip":"RADR",
"ris":"TAK",
"risk":"MQI BWGI",
"rivalry":"UKQB QVHJ",
"river":"ISKG",
"road":"KHTK",
"roadsid":"KHTK LPV",
"roam":"IJLC HIR",
"roar":"KDGT",
"rob":"RWBN FCLN",
"robert":"LQU WRG TRFF",
"robin":"LQU PRGW",
"robinson":"LQU PRGW BIPI",
"robot":"SMN KKDK WWWW",
"robust":"WVFP UFG",
"rock":"DGTG",
"rocket":"OOOO TUEJ",
"rocky":"DGTG UDI RQYY",
"rod":"SFH",
"roebuck":"DCWY QTQN",
"rol":"QEJ QCB",
"rom":"KWU YFND DHBD WYFJ KKDK",
"roman":"LQU CNNG",
"roof":"NGCF SDMY",
"room":"YNYV UJD",
"rooney":"QGJF NXV",
"root":"SVEY",
"ros":"GTY GRQC",
"rot":"YWFW OUFG",
"rough":"OEGG OTFP",
"round":"LKMI",
"rout":"TAVN YQAY RWI MTY",
"routin":"IPKH FWMQ",
"rov":"IJLC IYTB",
"row":"RDJD",
"rub":"RPVG YSSR",
"rugby":"SNBT SJTQ GFIY",
"ruin":"VAMC",
"rul":"FWMQ TDAN",
"rum":"YVCE VXGU",
"rumbl":"BTGG BTGG FNR",
"run":"KHQN",
"run-up":"TAK FHNV",
"rush":"DFAJ",
"rut":"IPKH FWMQ",
"sack":"WAYE",
"sacramento":"ABUT DQB RUG UYHN RTAN",
"sad":"DJDN",
"sag":"GHI BTAH",
"said":"YUKQ",
"sail":"MHMY",
"saint":"CFF TFHY",
"sal":"FNUD",
"salt":"FHLF",
"salv":"PVF NFIN",
"sam":"FBN CFY PWAF NFU XUJF",
"sampl":"SUDH KKKF",
"samsung":"DGGG JTGF",
"sand":"IITT",
"sandwich":"DGGG JEG ICKG",
"sank":"IPMN",
"santiago":"CFF FBN GOGD SKSK",
"sap":"IYWY",
"sass":"OEGG QGJF",
"sat":"WWFF",
"satellit":"BGD JTGF",
"satisfy":"IAGW KHU",
"saturday":"JTGF ADWE UYGY",
"saturn":"FFFF JTGF",
"sav":"FIYT",
"saw":"QNDG",
"say":"YUKQ",
"scal":"TFFU XEYY",
"scam":"YTHF CYNA",
"scan":"RVG RALG",
"scar":"UCV",
"scat":"FHU GAK",
"schedule":"YFH AJH",
"scheduled":"YFH AJH",
"scheme":"YYGN PVSU",
"school":"IPBF SUQY",
"schools":"IPBF SUQY",
"schwab":"YTBN GNYN DMHJ",
"schwarzenegger":"YTBN GNYN UYGH STKG",
"scor":"TJGF WVB",
"scot":"ALWU STKG UFF WWWW",
"scotland":"ALWU STKG UFF",
"scrap":"DYWF THGN",
"screen":"NUAK AJDH",
"screens":"NUAK AJDH",
"screensaver":"NUAK WKSY",
"scrutiny":"CMQN PWFI",
"sea":"ITXU",
"seal":"ITXU EEQY",
"sear":"OQYY",
"search":"RAT",
"season":"TBF",
"season-ending":"TBF GSI",
"season-high":"JGG TBF",
"seat":"YWWF",
"seattl":"SGHG AHTY LTUI",
"sec":"GGLL WFCU QTN",
"second":"TXHT FGG",
"second-biggest":"TXHT FGG DDDD",
"second-half":"GHI UFK FNRT",
"second-largest":"TXHT FGG DDDD",
"secret":"TNTT PNTM",
"secretary-general":"TNTT NNHY TAYI",
"sect":"FTBT IREY",
"see":"RHF",
"seek":"VFU",
"seem":"RHF FHNV GOI",
"seen":"RHF MQB",
"seiz":"RRHY WYGG",
"select":"TFQP",
"semi-final":"UFK UNWY PFJM",
"semi-finals":"UFK UNWY PFJM",
"semiconduc":"UFK NFU WSGG",
"sen.":"LGYI PEU WGKU YNN RYNT FGHG",
"send":"UDPI",
"sens":"DGKN IPMQ",
"sent":"UDPI",
"sep":"VTN EEEE",
"sept":"VTN EEEE",
"sept.":"VTN EEEE",
"sequel":"XFKG JSI",
"serb":"PFJF QIU XWYG GOGD",
"serv":"EBCY TLB",
"set":"PVF LFHF",
"setback":"RWWF RRH",
"settl":"QEVH UNWY",
"seven":"AGN",
"sex":"NTGG",
"shadow":"BEG JYIE",
"shak":"RUFH",
"shaky":"YLKM RUFH",
"sham":"HAOG WNHC",
"shap":"GAET",
"sharapov":"IITT RUG IHCY FWI",
"shark":"IITG QGF",
"sharp":"IDU",
"sharply":"IDU YNTJ",
"shed":"AAAA SEEG",
"sheet":"YSI UJFJ",
"sheikh":"YTMF FOFO",
"shelv":"RUTK LFHF",
"shield":"RFHD",
"shift":"RVFB",
"shin":"ECAG",
"ship":"TEMK",
"shock":"FDFE NYIY",
"shoot":"TMDF",
"shootout":"SWBN HKAT",
"shop":"UMWK YHKD",
"shor":"IPRW",
"short":"TDGU",
"short-term":"TDGU ADWE",
"shortfal":"GII KHU",
"shot":"TMDF FMK",
"show":"RHF",
"showcas":"NAEI FIU",
"showdown":"CFY UNWY",
"shown":"JOGF BMK",
"shrine":"CFF NAWC",
"shrugged":"WWBF",
"shut":"UDU",
"shutout":"PFQB ETGG",
"shuttl":"SCWT",
"shy":"EDMD EMAW",
"sick":"UGMW",
"sid":"DMJD",
"sidelin":"UVOU BKWY",
"sieg":"LFNH",
"sight":"PYMQ LTN",
"sign":"TWFU KGNB",
"silicon":"DFFG",
"simil":"TTDU",
"simon":"SGHG APGE",
"simpl":"TUJF UJFJ",
"simply":"TUJF UJFJ",
"sin":"LDJD",
"sina":"USRH IYVE",
"sing":"KJJG",
"singl":"QTJY",
"sink":"IPMN",
"sir":"TFQB TGD",
"siri":"",
"sit":"WWFF",
"six":"UYGY",
"six-month":"UYGY EEEE",
"six-year":"UYGY RHFK",
"size=":"DDDD IHTY",
"skat":"UIY AFFF",
"ski":"IMEG FVF",
"skin":"HCI EFWY",
"skip":"KHIQ",
"sky":"GDI",
"slain":"QSU",
"slam":"RGUH FMK",
"slap":"RRG RSH",
"slash":"DQWY",
"slat":"SRCY",
"sleep":"HTGF",
"slew":"QVNU LFNY",
"slic":"THGN",
"slid":"IMEG TFHH",
"slight":"IHTY",
"slim":"ALF TSU",
"slip":"IMEG WGCJ",
"slovak":"ADWR ITKG WAT DQB",
"slow":"NJLC",
"slowdown":"YKGE VEPI",
"slug":"GGLL KKKK",
"slum":"WVMU NAV PWNM",
"slump":"QTBL KHRW",
"smallest":"JBCU IHTY",
"smart":"BUKN JEG",
"smartphon":"TDKJ CEXX RTGH SMN",
"smash":"RSH ONRH",
"smi":"UFK",
"smil":"TTDU",
"smok":"OLDY",
"smuggl":"FHU TCY",
"snatch":"RWBN",
"sneak":"IQYL",
"snow":"FVF",
"so-called":"RNRH YLEG RQYY",
"soar":"YMKF NUI",
"soft":"LQWY",
"soil":"FFFF FYKE",
"sol":"YQAY",
"sold":"FNUD",
"solicit":"FPXI FIYI",
"solid":"LDD WSGG",
"solv":"QEVH UNWY",
"som":"GGLL HXFF",
"someon":"AFSU WWWW",
"someth":"AFSU GKVH",
"sometim":"AFSU JFY",
"somewh":"AFSU FBN",
"son":"QTN BBBB",
"song":"SKSW",
"sony":"FPXI NXV",
"soon":"CNNG HHGG",
"sor":"UCEK",
"sort":"TKHH ODU",
"sought":"VFU RAT",
"sound":"FNR",
"sourc":"IDRI",
"southampton":"FMUF PVF UOGJ GBNM",
"southeast":"AII FMUF",
"southeastern":"AII FMUF RQYY",
"southern":"FMUF YYGN RQYY",
"southwest":"SGHG FMUF",
"southwestern":"SGHG FMUF RQYY",
"soviet":"ALWU BUDY",
"sox":"TDGU PUGS",
"spa":"IIII UBK",
"spac":"PWAF UJD",
"spacecraft":"PGFJ PMF NUI TEMK",
"spain":"SGHG GYTG AHTE",
"spam":"FUG FEYY MBH WRHH",
"span":"KHDN YACI",
"spaniard":"SGHG GYTG AHTE WWWW",
"spar":"QVHJ YWXN",
"spark":"OOOO AWXB",
"spat":"QVHJ KITT",
"spawn":"QYTY",
"speak":"YUKQ",
"spec":"DUOG FCPI RNB",
"speech":"IPGW YFJH",
"speedway":"YSSR RTAN LGNH PFJM",
"speedy":"NFPK GKIP",
"spend":"AWXB XJMU",
"spent":"AWXB XJMU",
"spik":"GMIJ",
"spin":"LFNY",
"spirit":"OGEG PYJH",
"spit":"KFG",
"spitz":"QTRY QTJF DGTY",
"split":"AVN GAK",
"spoil":"PDXB",
"sport":"FCPI FCLN",
"spot":"HKOU",
"spotlight":"BCTI IQB OSH",
"sprained":"RNFG WTLN",
"spread":"NAEI GAK",
"spreading":"NAEI GAK",
"spring":"DWJF GDI",
"sprint":"TDGU KHQN",
"sprinter":"TDGU KHQN FCPI FCLN KMU",
"sprinters":"TDGU KHQN FCPI FCLN KMU",
"spur":"IRYT DDNL",
"spurry":"UTDI FHU",
"spy":"UJD YANS",
"squad":"FCPI FCLN BWY",
"squeez":"SPWF",
"stabl":"TQVN",
"stack":"SGT",
"staff":"BKWY KMU",
"stag":"CKF",
"stak":"SYFG",
"stal":"GII USRH QGUD",
"stamp":"MBH NWYA",
"stand":"UHKG",
"standard":"SFIY UWYG",
"stanford":"ADWR FJGG PYGL",
"stanley":"ADWR FJGG TJH",
"stapl":"QSH NNHY QFH",
"star":"JTGF",
"start":"GAK VCKG",
"start-up":"YNKD FCLN",
"startup":"YNKD FCLN",
"stat":"YTYH",
"state-owned":"LGYI DEF RQYY",
"state-run":"LGYI DEF RQYY",
"stay":"WYPS",
"steady":"TQVN",
"steam":"ABIO IRNN",
"steel":"QMQY",
"steep":"BFHY",
"stem":"SGJQ",
"step":"HIR",
"stern":"ASKF YNTJ RQYY",
"steroid":"ODU LDD SGYB",
"stick":"SJXX",
"stiff":"DGJQ",
"stifl":"RDBN QSU",
"stil":"WEN",
"sting":"RVYJ",
"stir":"RIPQ",
"stock":"EMCY AII",
"stockholm":"ADWR TFLN SKSW QIU YSSR",
"stockpil":"WYFJ TLF TRQR UQWM",
"stok":"LKG IMG",
"ston":"DGTG",
"stood":"UHKG",
"stop":"WYPS",
"stor":"UMWK YHKD",
"storm":"JAWI MQI FGHY",
"story":"DTY GKVH",
"straight":"FHF",
"strain":"DFYI LTN",
"strained":"JCXI XTAY",
"strange":"DSKF NCFG",
"strategic":"HKAT LTKG RQYY",
"strategy":"HKAT LTKG",
"straw":"KEYY TPNN",
"streak":"TSU",
"street":"TFFH",
"streets":"TFFH",
"strength":"LTN JGJF",
"strengthen":"LKG LDD",
"stressed":"GII PVF RQYY",
"stretch":"RUG WJHH",
"stretched":"RUG WJHH",
"strike":"FMK",
"striker":"UEJJ QTDH",
"strikes":"FMK",
"striking":"NYIY WWWW RQYY",
"string":"XGT",
"strip":"EUKQ",
"stripped":"EUKQ",
"stroke":"FMK",
"strokes":"FMK",
"strong":"XKJY",
"stronger":"GJQI XKJY",
"strongest":"JBCU XKJY",
"stronghold":"WKSF CCCF",
"strongly":"XKJY UFG FBN",
"struck":"FMK",
"structure":"XFKG SQCY",
"struggle":"UFK QVHJ",
"struggled":"UFK QVHJ",
"struggles":"UFK QVHJ",
"struggling":"UFK QVHJ",
"stuck":"RTFV",
"stud":"BGHG QSH",
"studio":"AAAA WTHF PGCF",
"study":"IPBF",
"stuff":"AII SGHG",
"stumbl":"XUFH",
"stun":"RSH JPLJ",
"styl":"MQI STKG",
"subject":"YGD JGHM",
"submarin":"IFWJ TETP",
"submit":"RJGH UQU",
"subscrib":"YSH MQCY",
"subsidy":"PUHY MHKG",
"subst":"WVB XEGG",
"suburb":"UQBH AQI",
"success":"DNNT ALN",
"sudanes":"ALWU MYD",
"sue":"FHNV YRYY",
"sued":"FHNV YRYY",
"suggest":"VFHP YYQY",
"suicid":"THD QSU",
"suing":"FHNV YRYY",
"suit":"DDU UFYE",
"sum":"TKG",
"summit":"MMMM SDMY",
"sun":"DYI BJG",
"sunday":"JTGF ADWE GDI",
"supercomput":"FHVK XEYY YFH THAJ SMN",
"supermarket":"FHVK YMHJ",
"supply":"RJGH WAWY",
"support":"FCU RFFY",
"suppos":"YWY YLYI",
"surf":"UKHH IYVE",
"surfac":"GEU DMJD",
"surg":"IRYT FULJ",
"surgery":"RTGH SYI",
"surpass":"ETGG FPI",
"surround":"GGIY XATQ",
"survey":"YMFK SJGF",
"suspect":"NGIY XTDH",
"suspend":"EGCN RFFG",
"sustain":"XWYG RFFY",
"sven":"IYCQ IYVE WGIJ PTKF",
"swap":"RQMD",
"swarm":"DDDD VTKD",
"swed":"GMDJ MAWU",
"sweep":"RVG",
"sweet":"TDAF",
"swept":"IGEG RVG",
"swift":"NFPK GKIP",
"swim":"IYTB IYNI",
"swing":"RLFC FCLN",
"swiss":"GMDJ FGHG",
"switch":"LFNY RQMD",
"switzerland":"GMDJ FGHG",
"sworn":"NTCY RRYF",
"swung":"RLFC FCLN",
"sydney":"TONU NXV",
"symantec":"PFJM UYHN QRWY DQB",
"symbol":"TWFU KGNB",
"system":"TXIU XYCQ",
"tab":"SFIY TWGI",
"tabl":"HJSU",
"tackl":"THI GJFG",
"tact":"TJGF WSGG",
"tag":"THGF",
"tail":"NTFN",
"tailback":"TAYI BWY",
"taiwanes":"CKF IYOX WWWW",
"tak":"GKPH",
"tal":"DTY GKVH",
"talk":"YUKQ",
"tamil":"DWIU OYTY QIU WWWW",
"tamp":"DLB PUDU",
"tank":"FJGG DQB",
"tap":"RMG",
"target":"HHHH SFIY",
"task":"WTFG TLB",
"tast":"KFIY UTHP",
"tat":"XYNA XKWY",
"tax":"TUKQ",
"tea":"AWSU",
"teach":"FTBT",
"team":"BWY",
"tear":"RADR",
"tee":"GFIY YWWF",
"teen":"GEF ITR RHFK",
"tel":"JNV YTDG",
"telegraph":"JNV RBCY",
"telephon":"JNV YTDG",
"telephony":"JNV YTDG CEPK WYG",
"telescop":"YNEG FQPV QUJQ",
"temp":"JTYJ JFY AAAA",
"templ":"PYJH NAWC",
"ten":"FGH",
"tend":"FHQV TMKD",
"tent":"MHTY TTDP",
"term":"ADWE",
"terry":"XKWY TRQR",
"test":"IMJH YAAG",
"testimony":"YGHG YNGK",
"text":"YYGY SGD",
"textil":"XYN XKWY KKKF",
"thailand":"DWIU LGYI",
"thank":"YTMF",
"thatch":"ACBT AJJ",
"theft":"WWGJ",
"themselv":"WBN WUN THD NNGN",
"thes":"YPI HXFF",
"thick":"DJBD",
"thin":"UVHC",
"thing":"AII SGHG",
"think":"SHNU",
"third":"TXHT DGGG",
"third-generation":"TXHT DGGG WAY",
"third-largest":"TXHT DGGG DDDD",
"third-quarter":"TXHT DGGG TBF YACI",
"thompson":"INRT UOGJ SSSU",
"thomson":"INRT VXGU SSSU",
"though":"NYUU TPNN",
"thought":"SHNU",
"thousand":"TFK",
"threat":"AMYN KGHY",
"threaten":"AMYN KGHY",
"threatened":"EPCU GCFJ DGVT ELWY RQYY",
"threatening":"DGVT ELWY RQYY",
"threatens":"AMYN KGHY",
"threats":"AMYN KGHY",
"three":"DGGG",
"three-day":"DGGG GDI",
"three-game":"DGGG WHJ IYTB CAT",
"three-month":"DGGG WHJ EEEE",
"three-week":"DGGG MFKD",
"three-year":"DGGG RHFK",
"threw":"RMCY RUDB",
"thrilling":"WYCU WWWW IWU DLF RQYY",
"throne":"PGYU YWWF",
"throughout":"YNMP EYI",
"throw":"RMCY RUDB",
"throwing":"RMCY RUDB ADMY HHHH",
"thrown":"RMCY RUDB",
"throws":"RMCY RUDB",
"thursday":"JTGF ADWE LHNG",
"thwart":"BEGG RATQ",
"tick":"HEPH UJD",
"ticket":"SFIU",
"tid":"IFJE",
"tie":"RLSY",
"tig":"RKHY OPI ADNT",
"tight":"JCXI",
"tim":"JFY UJD",
"tiny":"GKIH IFKG",
"tip":"SDMY",
"tir":"UHCI APLB",
"tit":"VEN BBBB",
"titl":"SFIY JGHM",
"tobacco":"OLDY",
"tod":"QTJY THD",
"today":"WYNB GDI",
"tokyo":"AII YIU",
"told":"TFKF YRYY",
"tom":"INRT VXGU",
"tommy":"INRT OYTY",
"tomorrow":"JEG GDI",
"ton":"KGBN",
"tonight":"WYNB YWTY",
"tony":"RTAN NXV",
"took":"GKPH",
"tool":"AAAA HWU",
"top":"SDMY",
"top-ranked":"XEYY KLJH JBCU YMKF",
"top-seeded":"UDI KGNB TKHH BBBB",
"toppl":"FHWM STTT",
"tor":"RADR",
"torn":"RADR",
"toronto":"QQU WWXN QQU",
"tort":"WVPC SCY",
"toss":"REN",
"tot":"XLN QTN",
"touch":"QEJY",
"touchdown":"UDHF BFMH",
"tough":"JCFF LDD",
"tour":"YTEY TFHH",
"tout":"WGCJ FNUD",
"tow":"RTBN",
"toward":"TMKD",
"town":"FDNT QFHW",
"toy":"GFQN HWU",
"trac":"YOPI",
"track":"KHU YOPI",
"trad":"QYVM JQRR",
"trademark":"UMWK SFIY",
"traffick":"UQU CEPK",
"tragedy":"POU CWYG",
"trail":"IHTY TCAG",
"train":"YKH XANW",
"transact":"THI GJFG",
"transform":"NTY YOCU",
"transit":"FCPI LWGJ",
"transmit":"WFNY RTOL",
"transport":"FCPI LWGJ",
"trap":"BQVG BFJH",
"travel":"YTEY TFHH",
"treasury":"UQWM QQQQ",
"treaty":"TSU XQYY",
"trend":"FHQV RVYL",
"tribun":"YFJH FFCY",
"tribut":"GCFT AQKT",
"trick":"YQDB YFH",
"trim":"WHTE",
"trio":"DGGG TGJF DWGD",
"trip":"YTEY TFHH",
"tripl":"DGGG TGJF",
"triumph":"TGJF DDDD DNNT YIDN",
"trod":"FHU",
"troop":"UKBH BWY",
"troubl":"YSSI ODMY",
"troy":"QQQQ TQDH",
"truc":"WSY HKAT",
"truck":"HHU LGNH",
"trump":"GGGG THGF",
"trust":"WYG",
"try":"YAAG",
"tuesday":"JTGF ADWE FGG",
"tumbl":"KHRW WGCJ",
"tun":"ISGG SCEH",
"tunnel":"BUEP UTHP",
"turf":"AJJ FBN",
"turk":"FFFF BGHG ADWU WWWW",
"turkey":"FFFF BGHG ADWU",
"turmoil":"IJXX TDNN",
"turn":"LFNY",
"turnaround":"TAVN YQAY NTY YOCU",
"tv":"JNV PYMQ",
"twic":"GMWW",
"twin":"CCY EQNN ECKG",
"twist":"XYJF",
"two":"FGG",
"two-day":"GMWW GDI",
"two-run":"GMWW WVB",
"two-thirds":"DGGG WVB PPPP FGG",
"two-time":"BMK FNUD",
"two-week":"GMWW MFKD",
"two-year":"GMWW RHFK",
"tycoon":"AND UDI",
"tying":"RLSY",
"typ":"ODU GAJF",
"typhoon":"CKF MQI",
"u.n.":"BUDY WGKF LGYI",
"u.s":"UGDU LGYI",
"u.s.":"UGDU LGYI",
"ucl":"WWXN YBTY DDDD IPBF IPBF BPFQ",
"uef":"FBN GFIY BUDY JELF",
"uk":"AMDU LGYI",
"ukrain":"QNGD DQB UFF",
"un":"BUDY WGKF LGYI",
"uncertain":"GII DQEH PGHU",
"uncertainty":"GII DQEH PGHU NTGG",
"unchang":"GII YOCU",
"unclear":"GII IGEG SSNH",
"undergo":"XCAG DLV",
"underground":"WQAY GHI",
"underlin":"XKJY YMFK",
"undermin":"DHCY FGIY",
"understand":"GJFG QEVH",
"underway":"FJPK TFHH KHK",
"unexpect":"BMK TUHK UJNU OUFH",
"unfair":"GII WCU GHD",
"uniform":"RMHJ EBCY",
"unit":"UJFJ FQB",
"univers":"PGFJ PMF",
"unix":"",
"unknown":"GII TDKG UTHP",
"unleash":"RUVG QEJY",
"unless":"BWTY DJDD",
"unlik":"GII WQJE",
"unman":"GII WQBJ WUN",
"unrest":"FCLN TDNN",
"unveil":"RJQN AJDH",
"upgrad":"RJGH TAK",
"upheld":"FCU RFFY",
"upon":"RUVG RPK",
"upr":"GII QNQN TKG BCTI SGXJ SCFY EXJG",
"upset":"RSH TDNN",
"upstart":"NTCY YOPI",
"upward":"TMKD HHGG",
"urg":"JCXI QVNU",
"us":"UGDU LGYI",
"us-based":"ADWF GFK UGDU LGYI",
"us-led":"UGDU LGYI YGD NFU",
"usc":"FMUF LKG YTYH DDDD IPBF",
"ut":"QTDN WBN",
"utah":"QTDN WBN",
"vac":"WSY WNHC",
"vaccin":"UMCI ALF",
"valenc":"YSI MHJC",
"valentino":"WXFJ WWXN GDI VCY",
"valley":"MMMM WWKF",
"valu":"WWJH WFHG",
"van":"YNYV LGNH",
"vary":"YOCU WXN",
"vast":"DDDD JGJF",
"vault":"KHIQ",
"venezuel":"TVF MWI GMDJ RUG",
"vent":"BMK KKKK",
"venu":"NTCY TGD FBN HKOU",
"verdict":"FAYE UNWY",
"verg":"RUVG RPK",
"verizon":"DGVT GMDJ SSSU",
"vers":"YFFY",
"vet":"ULGK ATDI",
"via":"XCAG FPI",
"victim":"EPCU PDHK FTJF",
"video":"PYMQ HIDM",
"videotap":"VIU WQJE",
"vienn":"XWYG BNHN XMWY",
"vietnam":"FHAT FMUF",
"view":"CMQN HKOU",
"vil":"AHTB GOGN",
"viol":"XWYG TMOD QIU GGWN",
"virgin":"THI VVVV",
"virus":"UGMW GXGU",
"visit":"YYN UKD",
"vital":"NTE SVF",
"vodafon":"ITDY DPI DHK",
"voic":"FNR",
"volatil":"RPLH NTCY",
"volcano":"OOOO MMMM",
"volleybal":"RDJD GFIY",
"volum":"JGJF",
"vot":"SFIU",
"vow":"RRYF",
"vs.":"",
"wad":"LFTE",
"wag":"RERM RLFC",
"wait":"TFFU",
"waiv":"YTY YCAJ",
"wak":"SGJG",
"wal-mart":"ITDY QIU GCG",
"walk":"FHU",
"wallet":"QGT QNV",
"wan":"NWYO NYWF",
"want":"SVF",
"war":"HKAT QVHJ",
"war-torn":"HKAT OOOO KHCS KHAY",
"ward":"UGMW YNYV",
"warlord":"PLJ UWAE",
"warm":"JEFC",
"warn":"AQKY TFKF",
"wash":"UKHH",
"washington":"WXFJ DNNL GBNM",
"wast":"IYVE XJMU",
"watch":"RHF",
"watchdog":"RHF UYHN QTQK",
"wav":"IYVE",
"way":"KHTK",
"weak":"XUXU",
"weaker-than-expected":"XUXU GFK CBDM ADWE",
"weal":"XAG EKHH",
"weapon":"GAHD KKDK",
"wear":"PWAT",
"web":"MQQI",
"web-based":"ADWF GFK MQQI XTKG",
"websit":"MQQI UHKG",
"wed":"XFKG VQAJ",
"wednesday":"JTGF ADWE DGGG",
"week":"MFKD",
"weekend":"MFKD GSI",
"weigh":"TQIY TGJF",
"weight":"TGJF JGJF",
"welcom":"CQWY QBPK",
"went":"FHU",
"wer":"JGHU",
"west":"SGHG",
"western":"SGHG LPV RQYY",
"westwood":"TMKD SGHG",
"whal":"QGYI",
"wheel":"LWXN",
"wher":"KVFB",
"whil":"ADWE UJD",
"whit":"GGLL HKOU",
"whol":"WGF",
"whos":"YWYG",
"wicket":"IHTY UYHN",
"wid":"PAMQ",
"widespread":"YYGT ITPY",
"wif":"GVHV",
"wil":"UQFY",
"wild":"JFCB",
"wild-card":"CEPK SGNN TWFU",
"william":"DGVT YUVO",
"willingham":"DGVT YUVO DBV VXGU",
"wilson":"DGVT QIU BIPI",
"win":"YNKY",
"wind":"MQI",
"window":"PWTQ",
"wing":"FCND EUPY",
"wip":"RPWI",
"wir":"XGT",
"wireless":"FQV XGT",
"wisconsin":"DGVT ADWR YVII JTGF",
"wish":"QDMH YNEG",
"wit":"MQI FHBC",
"withdraw":"RYCT",
"withdrawn":"RYCT",
"withdrew":"RYCT",
"within":"JFD DMJD",
"without":"IMCY DEF",
"wizard":"LLB AWWI",
"wnba":"",
"woe":"UCEK ADF",
"won":"YNKY",
"wood":"SSSS",
"word":"UJFJ YNGK",
"work":"AAAA WTHF",
"workforc":"APLB FCLN LTN",
"world":"ANV LWJJ",
"worldwid":"ANV LWJJ AIBB LFNH",
"worm":"JFDJ JHNY",
"worry":"RJGG NYNY",
"wors":"GJQI FGIY",
"worst":"JBCU FGIY RQYY",
"would":"UQFY SVF",
"wouldn":"GII WFCU",
"wound":"EPCU WTLN",
"wrap":"YJSE",
"wreck":"RWI GKVH",
"wrestl":"RNFG RSH",
"wright":"AAAA WWWW",
"wrigley":"TUEJ THGF",
"wrist":"EPQB",
"writ":"WYCU",
"wrong":"QAJG",
"wrot":"PGNG",
"wta":"VVVV BBBB MQQI GFIY FLWY WFCU",
"wto":"ANV LWJJ QYVM JQRR XEGG XKWY",
"xbox":"",
"xinhuanet":"USRH WXFJ MQQI",
"yahoo":"AHTY HAMV",
"yank":"QTBL RUG",
"yao":"VIQN",
"yard":"BPFQ",
"year":"RHFK",
"year-end":"RHFK XTUY",
"yellow":"AMWU",
"yen":"IJQN YNEG",
"yesterday":"JTHF GDI",
"yet":"WJGG JGHU",
"yield":"UTE",
"york":"XQYY DQB",
"young":"RHFK LCAG",
"yu":"TKMY",
"yudhoyono":"CCCC QQU XQYY YADK",
"yugoslav":"FMUF ADWR RUG FWI",
"yuko":"INRT DGHG",
"yushchenko":"DNV TFQB TUFH",
"zealand":"SGHG UFF QYNM",
"ziff":"DEG EDMY",
"zimbabw":"IVFH CNHN DMHJ FNHK",
"zon":"FBN GKPH",
"zurich":"ALWU TQTI ANV",
}